### ISSUE TITLE
Sideways Dark Oak Log missing texture

### ISSUE THREAD

**Issue by jwalty** [CreativeMD/LittleTiles#400] opened 2020-05-11 14:11 UTC
Sideways Dark Oak Logs placed in the world are showing as missing textures named 'Oak Wood' in advanced recipes and little bags

Omnifactory 1.2.2
LittleTiles_v1.5.0-pre199_19_mc1.12.2.jar
CreativeCore_v1.10.10_mc1.12.2

![11_10_08_12](https://user-images.githubusercontent.com/1341835/81572007-ad387500-9370-11ea-87ed-9067d76e35bb.png)

Link to video of bug: https://puu.sh/FJ3f0/7246bbc058.mp4

**Comment by CreativeMD** [comment] 2020-05-12 13:55
The question how have you obtained those? (It shouldn't be possible using LT at least not in the newer versions).

**Comment by jwalty** [comment] 2020-05-12 13:58
I placed regular dark oak logs into the little bag, made a miniature of the structure containing sideways dark oak logs, and then all the logs in the bag were converted to the untextured and sideways dark oak logs called “Oak Wood”

**Comment by CreativeMD** [comment] 2020-05-14 07:57
I can't reproduce it. Everything worked just fine for me. Can you record a video of how you get it?

**Comment by jwalty** [comment] 2020-05-14 15:12
Here's a video on a fresh install for reference
https://www.youtube.com/watch?v=dvCUqhIPNII

**Comment by CreativeMD** [comment] 2020-05-14 17:07
Please update to the newest version of CreativeCore and LittleTiles, since it works absolutely fine for me.

**Comment by CreativeMD** [comment] 2020-05-18 09:04
I will close this issue for now. If you can reproduce it in the newest version make sure to post it here.

**Closed as completed by CreativeMD** 2020-05-18 09:04 UTC
