### ISSUE TITLE
[bug] tiles invisible on reloading world

### ISSUE THREAD

**Issue by AlienXtream** [CreativeMD/LittleTiles#440] opened 2020-07-07 14:31 UTC
really weird stuff happens when either re-logging into the world or leaving and returning to the chunks.

-invisible until a chunk redraw (placing block or other update)
-Animated doors invisible after dim change/unloading chunks until reloading world
-still invisible tiles AFTER chunk redraw. 
im using a custom kitchen sink pack but nothing fancy with rendering is being done in the instances where the tiles are. only likely culprit i can think of is optifine (which is an absolute must. i like a playable frame rate and it's the only solution that works for me). i was using them heavily for large scale details like angled walls and floors to match the "curve"

i love this mod and the level of detail i can get with it. if there is any way to fix the stuff so it renders properly would be wonderful

here's how i was using them. sadly i deleted all the tiles before thinking to make a report so i cant exactly provide them

![2020-07-04_20 01 55_2](https://user-images.githubusercontent.com/12606809/86796335-d431cf80-c0b1-11ea-87f9-0bdc2fe53a9a.png)

this one "shows" the door bug. those ones were super persistent and it took reloading the whole game before they showed up again. i didn't even know they were still there when i took the screenshot (hence me using the 3x3 iron doors from malisis doors)

![2020-07-04_03 48 40](https://user-images.githubusercontent.com/12606809/86796597-19ee9800-c0b2-11ea-9248-15c1f7223675.png)

**Comment by AlienXtream** [comment] 2020-07-07 14:32
i know all this is SUPER vague but im not really sure what else i can provide :/

**Comment by kirokadura** [comment] 2020-07-07 15:17
What LittleTiles and CreativeCore versions are you using? The full .jar file names.

**Comment by AlienXtream** [comment] 2020-07-07 20:02
LittleTiles_1.5.0-pre199_3_mc1.12.2.jar
CreativeCore_v1.10.16_mv1.12.2.jar

both are the latest for my game version (1.12.2 if that wasn't already obvious from the second screenshot and the file names :P)

**Comment by AlienXtream** [comment] 2020-07-07 20:04
also the shading issues in the first image. separate issue but worth commenting on.

**Comment by AlienXtream** [comment] 2020-07-07 20:09
and yeh, i know i have a lot of mods and as such issues arise but if it works flawlessly on MY game then its pretty robust (and for the MOST part it does other than a couple quirks with shading and connected textures sometimes being wonky. these (animated doors and tiles vanishing) are the only BIG issue ive had so nice work :D)

**Comment by CreativeMD** [comment] 2020-07-08 09:06
Update LittleTiles your version is a little outdated.

**Comment by AlienXtream** [comment] 2020-07-08 17:36
well its the latest version on both twitch app AND curseforge. oh i see XD. i made a typo in the version number sorry XD
its pre199_34... my bad

**Comment by CreativeMD** [comment] 2020-07-09 08:19
Can you send me your world so I can do some testing?

**Comment by AlienXtream** [comment] 2020-07-09 08:46
shit, sorry man. deleted it due to other issues (not related to your mod). next best thing i can offer is a twitch launcher pack... if it will let me export

**Comment by AlienXtream** [comment] 2020-07-09 09:03
ok, so twitch client is being more broken than usual and wont let me export the pack so i will have to just send a mod list. and.... its long... like, as you can see in the screenshot with the debug screen up its over 400...

here is an older crash report that SHOULD have them all listed. i know its not ideal but short of typing the mods out one by one or twitch client behaving itself its the best i can do right now. note that the crash is 100% unrelated to your mod and is only to get you some form of list.

i do suspect optifine is the most likely candidate but as i mentioned before due to the size of my pack its a must for a playable framerate.

[crash-2020-07-08_19.08.09-client.txt](https://github.com/CreativeMD/LittleTiles/files/4895616/crash-2020-07-08_19.08.09-client.txt)

there's my OF settings if you wanted to throw that one into the mix and see if it alone breaks things (not tested with just LT and OF yet. honestly never occured to me till just now to even try)
[optionsof.txt](https://github.com/CreativeMD/LittleTiles/files/4895650/optionsof.txt)

i will TRY and get the app to behave itself in the meantime and get you an ACTUAL exported pack for testing.

**Comment by CreativeMD** [comment] 2020-08-28 20:20
I'm not sure. Is this still a problem?

**Comment by tom1422** [comment] 2020-08-29 10:26
I'm getting a similar issue. CreativeCore and Little Tiles are on latest 1.12.2

**Comment by CreativeMD** [comment] 2020-09-01 10:29
This is probably a duplicate of https://github.com/CreativeMD/LittleTiles/issues/440 (even though it was posted earlier). Try to get the newest version of CreativeCore and LittleTiles, maybe it's fixed. Would be very nice if you could post your results in the other issue.

**Closed as completed by CreativeMD** 2020-09-01 10:29 UTC
