### ISSUE TITLE
Little Chisel does not recognize blocks in my inventory or in the Little Bag

### ISSUE THREAD

**Issue by NinjaCheetah** [CreativeMD/LittleTiles#417] opened 2020-06-01 13:08 UTC
When I try to place to tiles with the Little Chisel, it says it needs more resources, even though I have several stacks of resources in both my inventory and the bag. When I try to select either in the chisel, it shows them but then refuses to place them.

**Comment by LordPensington** [comment] 2020-06-08 22:10
I have the same issue MC 1.12.2
You can overcome by using the Hammer and using it to destroy blocks of the needed Material. You also need the at least one Block in the inventory to be able to choose it.
Unfortunately on game restart, everything is gone again. Its very annoying.
The little Bag seems not to work at all. The same with dyes, if you fill them into the bag the right sound are played but the fill bars do not appear and its not usable.
I hope there will be a solution.

**Comment by CreativeMD** [comment] 2020-08-28 20:14
I can't reproduce this issue. Can you give me an example of what blocks you use? Maybe post a screenshot?

You can also try out the newest version and see if that fixes your issue? BUT BACKUP YOUR WORLD FIRST!
https://cdn.discordapp.com/attachments/326729168266199040/748915793831657502/CreativeCore_v1.10.18_mc1.12.2.jar
https://cdn.discordapp.com/attachments/326729168266199040/748915823812280422/LittleTiles_v1.5.0-pre199_41_mc1.12.2.jar
https://cdn.discordapp.com/attachments/326729168266199040/745705002861068319/OnlinePicFrame_v1.5.0-pre1_mc1.12.2.jar

**Comment by CreativeMD** [comment] 2020-09-04 09:45
I will close this issue for now. If it still occurs in the newest version please make some screenshots so I can reproduce this issue myself.

**Closed as completed by CreativeMD** 2020-09-04 09:45 UTC
