### ISSUE TITLE
Minor Issue with "Tile Preview"

### ISSUE THREAD

**Issue by DonK4rma** [CreativeMD/LittleTiles#674] opened 2021-05-13 12:52 UTC
![image](https://user-images.githubusercontent.com/82897907/118128124-1dcd0400-b3c0-11eb-9350-eb9cd370e45d.png)

**Comment by CreativeMD** [comment] 2021-05-14 08:25
Can you export the structure so I can try to reproduce it?

**Comment by DonK4rma** [comment] 2021-05-16 14:44
i can send you the world cuz is very laggy

https://drive.google.com/drive/folders/1dLPWkeETPzDrHEpNqb2BQPD4zeRxlhMA?usp=sharing

**Comment by CreativeMD** [comment] 2021-05-17 10:44
can't reproduce it, can you show me a better screenshot? I need to know what exactly I need to do.

**Comment by DonK4rma** [comment] 2021-05-17 20:36
it basecally happens when you make a 1024 long side wall like structure and use the chissel tool to go to side to side

**Comment by ghost** [comment] 2021-05-17 22:14
yes i have the same some times. Er markiert nicht alles obwohl es makiert ist. Enweder am Anfang oder am Ende von dem was man markiert.

**Comment by ghost** [comment] 2021-05-19 18:25
5 Blöcke "Gefärbter Block rein" erstellt.

https://gyazo.com/5214bf0e29ac3c8fe9ef71eaa2750fea

Im Box Modus zurechtchiseln
https://gyazo.com/8d1cf17a1f9f7b92ec07c0e88906fa17

geht nicht bis zum Schluss

https://gyazo.com/9f84d3c367b8cb5d78dab16f4a620dac

und wenn ich um die Ecke gehe fehlt der Rahmen auch siehe Bild.

its fixed in the newest build.... Thanks CreativeMD!

**Comment by CreativeMD** [comment] 2021-05-24 10:12
Maybe fixed in the newest version. @DonK4rma can you test it?

**Comment by DonK4rma** [comment] 2021-05-25 12:52
> Maybe fixed in the newest version. @DonK4rma can you test it?

Yes ill check, i almost forgot about the problem

**Comment by DonK4rma** [comment] 2021-05-25 12:57
Seems to be working but the preview is messed up
![image](https://user-images.githubusercontent.com/82897907/119501798-d125e900-bd2e-11eb-95f3-379b7440749f.png)

**Comment by CreativeMD** [comment] 2021-05-25 14:49
The preview is always bigger than the actual tile. The grid size you are using is just too small.

**Closed as completed by CreativeMD** 2021-05-25 14:49 UTC
