### ISSUE TITLE
Advanced door misbehaving with unknown trigger.

### ISSUE THREAD

**Issue by thecheesemo** [CreativeMD/LittleTiles#777] opened 2021-11-02 00:55 UTC
I am coming from the Discord, Kiro suggested i post this here. I have made a two advanced doors to act as double doors. they both open by sliding "out" a small amount then left or right. I have encountered two separate issues with them and have managed to get both on camera. My game details are below.

Issue 1: the door appears to open as normal, but i can not walk through the doorway and the door "disappears" just after starting the animation to close it. after it disappears, i can still not walk through the door way. Breaking and replacing the door seems to stop this behavior and its functions normally. 
Video of Issue 1: https://vimeo.com/641237114 (this video doesn't show the initial opening as i didn't anticipate it happening this time.)

If i had to guess this issue feels like the server thinks the door is still closed and was never opened while and the client "loses" the door when it tries to close it. But i did a test where another player saw the door open, and had the same experience i did. 

Issue 2: at least once the doors were somehow in the open position and i was able to walk through the door way. However, when closing the door, it automatically opens up again. I encountered this Issue while trying to record a video for the first issue. Breaking and replacing the door seems to stop this behavior and its functions normally.
Video of issue 2: https://vimeo.com/641222654

Minecraft 1.12.2
Forge 1.12.2-14.23.5.2847
This is a custom modpack (modified E2:E) 
Server hosted on Bisect
CreativeCore 1.10.65
Little Tiles 1.5.33

Please let me know if you need any further details.

Thank you.

[Sliding Door LT.txt](https://github.com/CreativeMD/LittleTiles/files/7456942/Sliding.Door.LT.txt)
[Sliding Door RT.txt](https://github.com/CreativeMD/LittleTiles/files/7456943/Sliding.Door.RT.txt)

**Comment by CreativeMD** [comment] 2021-11-05 09:26
Issue 1 is as you have explained it. The door is closed on server side, but not on client side. There are many door issue at the moment and I'm very sorry to say that, but it won't be fixed. I'm currently working on porting this mod to 1.17 and it would take too long to fix it. You can however make the doors stay animated which works a lot better than normally.

Issue 2: no idea why that happens ... stay animated might also fix that.

For sorry for the bad news, I hope you can use this temporary fix. I will close this issue for now as it's a duplicate of https://github.com/CreativeMD/LittleTiles/issues/605 but you can still reply here if you need any further help.

**Closed as completed by CreativeMD** 2021-11-05 09:26 UTC
