### ISSUE TITLE
Client crash  - Gathering more information from the player.

### ISSUE THREAD

**Issue by ProsperCraft** [CreativeMD/LittleTiles#120] opened 2018-08-31 11:19 UTC
https://paste.dimdev.org/vobalununa.mccrash

This does not happen every time, as other players have loaded and logged in to the server without issues.

This is a fresh world.

**Comment by CreativeMD** [comment] 2018-08-31 11:28
Maybe try to use forge prior to 14.23.4.2759?

**Comment by CreativeMD** [comment] 2018-09-03 12:14
Okay Forge isn't the problem. Looks like an issue caused by another mod. Although LT appears in the crash-report something is messed up (not caused by LT). Maybe try to remove other mods and see if the crash still occurs?

**Comment by CreativeMD** [comment] 2018-09-09 13:34
Any news about this issue?

**Comment by ProsperCraft** [comment] 2018-09-09 22:57
I have not had any new reports of this happening

**Comment by CreativeMD** [comment] 2018-09-14 22:03
I will close it for now, just reopen it if it happens again.

**Closed as completed by CreativeMD** 2018-09-14 22:03 UTC
