### ISSUE TITLE
Uncertain what is going on, crash loop?

### ISSUE THREAD

**Issue by BSKCraft** [CreativeMD/LittleTiles#36] opened 2017-03-05 20:05 UTC
Just updated to the newest version and on existing and new worlds it hands on rendering/building world screen with a 0% and this is it until I force close. I looked at my logs and it is over 31 MB. 

http://pastebin.com/y8Ktq1G5 

this is just the first few sections, it repeats this section over and over until I force close.

http://pastebin.com/RKZ13AMe

Forge 1.11.2-13.20.0.2252
LT 1.4.0 

File too big to use pastebin or upload to here. So here is my DB link
https://www.dropbox.com/s/1808iv2r621nw99/latest.log?dl=0

**Comment by CreativeMD** [comment] 2017-03-05 20:40
Seems to be caused by a mod, but don't know which one is causing this issue.
Maybe some of the other coremods? Could you test it?

**Comment by BSKCraft** [comment] 2017-03-05 21:34
Sure thing, I reverted back to 1.3.10 and is working fine btw but I make another pack and go through to see what might be conflicting with it.

**Comment by CreativeMD** [comment] 2017-03-05 21:55
Ok that would be nice, because you should update to 1.4.0 (there were a lot of bug fixes, especially for doors)

**Comment by BSKCraft** [comment] 2017-03-05 21:59
Got it coach! Conflict with Mr. Crayfish's Furniture Mod 4.1.2 for 1.11.2. Hope this helps will also take the logs and post if over to his as well and link this issue, if I have to I can remove his mod until a fix can be made as I really want to try out your mod lol

**Comment by BSKCraft** [comment] 2017-03-05 22:06
Link to ticket for CFM - https://minecraft.curseforge.com/projects/mrcrayfish-furniture-mod/issues/14

**Comment by WenXin20** [comment] 2017-03-06 01:05
I had the same problem, but with Little Tiles 1.10.2-1.4.0 and with Mr. Crayfish's Furniture Mod.

**Comment by CreativeMD** [comment] 2017-03-06 11:18
Should be fixed in v1.4.1, which should be available in a few minutes.

**Closed as completed by CreativeMD** 2017-03-06 11:18 UTC
