### ISSUE TITLE
Crash When Placing Slice On Two Different Blocks

### ISSUE THREAD

**Issue by Doc-1** [CreativeMD/LittleTiles#466] opened 2020-08-23 15:08 UTC
When using the slice draw mode on the chisel if you select a min point on Block A that is larger than the max point on Block B it will crash. This was performed on the most recent GitHub pull. 

![slice crash](https://user-images.githubusercontent.com/45431412/90981581-d5b73a00-e52f-11ea-9af6-5ea5666ade92.gif)

```
WARNING: coremods are present:
  LittlePatchingLoader (LittleTilesLoader v1.0.jar)
  CreativePatchingLoader (CreativeCoreLoader v1.0.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 8/23/20 10:55 AM
Description: Unexpected error

java.lang.IllegalArgumentException: min has to be smaller than max!
	at com.creativemd.creativecore.common.utils.math.RangedBitSet.<init>(RangedBitSet.java:17)
	at com.creativemd.littletiles.common.tile.math.box.LittleBox.split(LittleBox.java:525)
	at com.creativemd.littletiles.common.tile.math.box.LittleBox.split(LittleBox.java:516)
	at com.creativemd.littletiles.common.tile.math.box.LittleBox.cutOut(LittleBox.java:547)
	at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.cutOut(TileEntityLittleTiles.java:515)
	at com.creativemd.littletiles.common.util.place.PlaceModeFill.placeTile(PlaceModeFill.java:40)
	at com.creativemd.littletiles.common.tile.place.PlacePreview.placeTile(PlacePreview.java:55)
	at com.creativemd.littletiles.common.util.place.Placement$PlacementBlock.lambda$1(Placement.java:457)
	at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.updateTilesSecretly(TileEntityLittleTiles.java:305)
	at com.creativemd.littletiles.common.util.place.Placement$PlacementBlock.place(Placement.java:443)
	at com.creativemd.littletiles.common.util.place.Placement.placeTiles(Placement.java:176)
	at com.creativemd.littletiles.common.util.place.Placement.place(Placement.java:160)
	at com.creativemd.littletiles.common.action.block.LittleActionPlaceStack.placeTile(LittleActionPlaceStack.java:148)
	at com.creativemd.littletiles.common.action.block.LittleActionPlaceStack.action(LittleActionPlaceStack.java:99)
	at com.creativemd.littletiles.common.action.LittleAction.execute(LittleAction.java:248)
	at com.creativemd.littletiles.common.event.LittleEventHandler.onRightInteractClient(LittleEventHandler.java:339)
	at com.creativemd.littletiles.common.event.LittleEventHandler.onInteract(LittleEventHandler.java:291)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_41_LittleEventHandler_onInteract_RightClickBlock.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1137)
	at net.minecraft.client.multiplayer.PlayerControllerMP.processRightClickBlock(PlayerControllerMP.java:430)
	at net.minecraft.client.Minecraft.rightClickMouse(Minecraft.java:1694)
	at net.minecraft.client.Minecraft.processKeyBinds(Minecraft.java:2381)
	at net.minecraft.client.Minecraft.runTickKeyboard(Minecraft.java:2147)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1935)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1188)
	at net.minecraft.client.Minecraft.run(Minecraft.java:442)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:25)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.creativemd.creativecore.common.utils.math.RangedBitSet.<init>(RangedBitSet.java:17)
	at com.creativemd.littletiles.common.tile.math.box.LittleBox.split(LittleBox.java:525)
	at com.creativemd.littletiles.common.tile.math.box.LittleBox.split(LittleBox.java:516)
	at com.creativemd.littletiles.common.tile.math.box.LittleBox.cutOut(LittleBox.java:547)
	at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.cutOut(TileEntityLittleTiles.java:515)
	at com.creativemd.littletiles.common.util.place.PlaceModeFill.placeTile(PlaceModeFill.java:40)
	at com.creativemd.littletiles.common.tile.place.PlacePreview.placeTile(PlacePreview.java:55)
	at com.creativemd.littletiles.common.util.place.Placement$PlacementBlock.lambda$1(Placement.java:457)
	at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.updateTilesSecretly(TileEntityLittleTiles.java:305)
	at com.creativemd.littletiles.common.util.place.Placement$PlacementBlock.place(Placement.java:443)
	at com.creativemd.littletiles.common.util.place.Placement.placeTiles(Placement.java:176)
	at com.creativemd.littletiles.common.util.place.Placement.place(Placement.java:160)
	at com.creativemd.littletiles.common.action.block.LittleActionPlaceStack.placeTile(LittleActionPlaceStack.java:148)
	at com.creativemd.littletiles.common.action.block.LittleActionPlaceStack.action(LittleActionPlaceStack.java:99)
	at com.creativemd.littletiles.common.action.LittleAction.execute(LittleAction.java:248)
	at com.creativemd.littletiles.common.event.LittleEventHandler.onRightInteractClient(LittleEventHandler.java:339)
	at com.creativemd.littletiles.common.event.LittleEventHandler.onInteract(LittleEventHandler.java:291)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_41_LittleEventHandler_onInteract_RightClickBlock.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1137)
	at net.minecraft.client.multiplayer.PlayerControllerMP.processRightClickBlock(PlayerControllerMP.java:430)
	at net.minecraft.client.Minecraft.rightClickMouse(Minecraft.java:1694)
	at net.minecraft.client.Minecraft.processKeyBinds(Minecraft.java:2381)
	at net.minecraft.client.Minecraft.runTickKeyboard(Minecraft.java:2147)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Player967'/64, l='MpServer', x=-184.02, y=4.00, z=551.81]]
	Chunk stats: MultiplayerChunkCache: 623, 623
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-138,4,500), Chunk: (at 6,0,4 in -9,31; contains blocks -144,0,496 to -129,255,511), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 299448 game time, 83077 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 21 total; [EntitySheep['Sheep'/32, l='MpServer', x=-121.66, y=4.00, z=553.22], EntitySheep['Sheep'/33, l='MpServer', x=-123.75, y=4.00, z=569.22], EntitySheep['Sheep'/34, l='MpServer', x=-117.60, y=4.00, z=581.21], EntityDonkey['Donkey'/35, l='MpServer', x=-104.80, y=4.00, z=482.58], EntitySheep['Sheep'/36, l='MpServer', x=-106.32, y=4.00, z=551.93], EntityItem['item.item.LTMultiTiles'/7, l='MpServer', x=-201.31, y=4.00, z=545.66], EntityItem['item.tile.grass'/8, l='MpServer', x=-203.44, y=3.00, z=552.88], EntitySheep['Sheep'/9, l='MpServer', x=-194.43, y=4.00, z=595.77], EntityPlayerSP['Player967'/64, l='MpServer', x=-184.02, y=4.00, z=551.81], EntitySheep['Sheep'/13, l='MpServer', x=-183.06, y=4.00, z=495.65], EntitySheep['Sheep'/14, l='MpServer', x=-168.80, y=4.00, z=581.68], EntityPig['Pig'/20, l='MpServer', x=-145.24, y=4.00, z=562.64], EntityItem['item.tile.grass'/83799, l='MpServer', x=-182.15, y=4.00, z=547.08], EntitySheep['Sheep'/24, l='MpServer', x=-130.45, y=4.00, z=531.75], EntitySheep['Sheep'/25, l='MpServer', x=-139.23, y=4.00, z=547.29], EntitySheep['Sheep'/26, l='MpServer', x=-132.45, y=4.00, z=558.26], EntitySheep['Sheep'/27, l='MpServer', x=-128.72, y=4.00, z=559.83], EntityPig['Pig'/28, l='MpServer', x=-133.79, y=4.00, z=575.21], EntityPig['Pig'/29, l='MpServer', x=-151.30, y=4.00, z=572.54], EntityPig['Pig'/30, l='MpServer', x=-137.81, y=4.00, z=577.22], EntityDonkey['Donkey'/31, l='MpServer', x=-123.81, y=4.00, z=543.56]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:461)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2889)
	at net.minecraft.client.Minecraft.run(Minecraft.java:471)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:25)

```

**Comment by CreativeMD** [comment] 2020-08-28 20:52
Issue should be fixed in the meantime (I could not reproduce it). If not tell me how to reproduce it exactly.

**Closed as completed by CreativeMD** 2020-08-28 20:52 UTC
