### ISSUE TITLE
Breaking tiles doesn't return any tiles.

### ISSUE THREAD

**Issue by CalderaTheArcane** [CreativeMD/LittleTiles#415] opened 2020-06-01 04:04 UTC
If i am holding the Little bag and i break some tiles with the little hammer it does not give me any tiles into my little bag nor does it give me any full blocks back into my inventory.

**Comment by CreativeMD** [comment] 2020-08-28 19:59
Can you test if this still occurs in the newest vesion:
https://cdn.discordapp.com/attachments/326729168266199040/748915793831657502/CreativeCore_v1.10.18_mc1.12.2.jar
https://cdn.discordapp.com/attachments/326729168266199040/748915823812280422/LittleTiles_v1.5.0-pre199_41_mc1.12.2.jar

If yes, make sure to post some screenshot (that makes it easier for me to follow).

**Comment by CreativeMD** [comment] 2020-09-04 09:09
I can't reproduce this issue in the newest version. I will close it for now. If it still happens for you (with the newest release on curseforge) make sure to contact me here again.

**Closed as completed by CreativeMD** 2020-09-04 09:09 UTC
