### ISSUE TITLE
Crash while positioning new slice wall in overwrite mode

### ISSUE THREAD

**Issue by tolerus** [CreativeMD/LittleTiles#651] opened 2021-04-24 23:05 UTC
Game crashes after placing first position of slice wall in overwrite mode while attempting to place second position using mark mode. I'll include logs from the three most recent crashes, most recent to the oldest. Most recent crash occurred in v1.5.4 and the other crashes occurred in v1.5.3

Please let me know if I can provide any further info! Thanks, as ever!

littleTiles_v1.5.4 log
https://paste.dimdev.org/utehuhiliy.pl

littleTiles_v1.5.3 logs
https://paste.dimdev.org/udilimihoh.md
https://paste.dimdev.org/wenaduxove.md

**Comment by CreativeMD** [comment] 2021-04-28 07:52
Can you try out the newest version v1.5.6 and see if it is fixed?

**Comment by tolerus** [comment] 2021-04-28 12:09
Still seems to have the problem!


https://paste.dimdev.org/akageqosig.md
^ Here's a test game I did.
There was a "slice" wall already placed, and I was attempting to place
another one directly next to it in overwrite mode on the same bias to the
grid as the "slice" wall already there. Game crashed while I was setting
the second placement point in mark mode.

I just have to say that your work on this mod is really, really impressive.
This makes Minecraft a completely different game; there are no limits on
the creative possibilities! These new features are really exciting and I
have a whole map full of littletiles structures and they just pop right up
the load times are so  fast now. Amazing!! Marry me.

Let me know if there's any more info I can provide for these crashes!

**Comment by CreativeMD** [comment] 2021-04-30 08:26
Can you send me a screenshot of that situation? I can't reproduce it.

**Comment by CreativeMD** [comment] 2021-05-04 12:39
Can you test if the newest version fixes this issue, if not please provide more information such as screenshots and export the structures so I can reproduce it.

**Comment by tolerus** [comment] 2021-05-04 14:48
Certainly! I'm traveling at the moment and unable to test it but I will as
soon as I'm able!

**Comment by CreativeMD** [comment] 2021-05-20 08:54
Any news?

**Comment by tolerus** [comment] 2021-05-21 14:52
I just got back home from traveling - death in the family

I'll test this and send through pics and blueprints for the shapes I'm
mashing together so you can hopefully recreate the problem. I'll do that
today! Thanks for your patience

**Comment by CreativeMD** [comment] 2021-05-21 15:30
Sad to hear that. Hope you are doing fun. No hurry, I just ask from time to time in case if someone forgot about it. This issue might be fixed in the newest version so if you can try that one as well (also update CreativeCore).

**Comment by tolerus** [comment] 2021-05-22 13:48
Thanks again for your patience; sorry I haven't been able to post this sooner! Drama in my family has been all-consuming and stressful.

The problem is still there with the update to 1.5.11 and here are some further details and steps to reproduce.

1. In creative mode, place this littleTiles blueprint of the apex of 2 angled walls with battlements:
    https://paste.dimdev.org/raw/tenurumora

2. See these pics of the placed blueprint, showing an attempt to place a new wall directly adjacent to one of the walls in the blueprint:
    https://imgur.com/a/xxlCnxT

3. Enter mark mode during wall placement to adjust the new "slice" wall, in overwrite mode. Crash occurs while adjusting the wall in mark mode, before the final click to place it. I sometimes have to place the wall on the ground to get the right shape, then raise it to the height of the crenellations before the crash occurs. 

(Additional info)- the blueprints I've created might be small but these are some rather complex blueprints made by overwriting slices with more slices. It may be that I'm just taking it a bit too far with how much overwriting slices I can have without creating issues. There aren't often glitches that crash the whole game, though, so I figured I'd better report it! Please let me know if there's anything further I can provide to help.

**Comment by CreativeMD** [comment] 2021-05-24 08:28
Can you send me the crash-report again? Also does this really only occur if you are using the overwrite mode? Because if this happens before you place anything I don't see how this could be related.

**Comment by tolerus** [comment] 2021-05-24 13:59
After a little more testing, if I'm in Fill Mode I can set the coordinates
for a new wall adjacent to the wall in this blueprint without any problems.
Then I switch over to Overwrite mode and before I have a chance to click
the final time to set the new wall, the game crashes. I'll keep
resetting and playing with positions in fill mode to see if I ever get a
crash but so far it has only happened
for me in overwrite mode. I'll post a new log if I can get it to crash in
fill mode too but so far that has never happened.

Here is a fresh crash report:

https://paste.dimdev.org/quperetecu.mccrash

and here is the complete log:

https://paste.dimdev.org/zojorurisu.pl

**Comment by tolerus** [comment] 2021-05-24 14:27
Yeah I just got a couple crashes in fill mode so you're correct; overwrite
mode must not be a factor

Here's a log for these crashes. VanillaFix is installed so I was able to
continue playing after the first crash. This log contains 2 game sessions.
First crash at line 2843, second crash at 3321

https://paste.dimdev.org/wehajupede.pl

**Comment by CreativeMD** [comment] 2021-05-27 10:19
It should be fixed in the newest version. Sorry for all the trouble. If the issue is still there just post it here.

**Closed as completed by CreativeMD** 2021-05-27 10:19 UTC

**Comment by tolerus** [comment] 2021-05-28 21:37
Great job! No trouble at all. Really looking forward to using all of these
great new features!
