### ISSUE TITLE
Error when opening door

### ISSUE THREAD

**Issue by Tschipp** [CreativeMD/LittleTiles#227] opened 2019-08-08 21:30 UTC
I'm not sure if this really is a problem with just LittleTiles or a multi-mod problem, but I sometimes get this crash when a door opens: 
[crash-2019-08-08_23.27.40-client.txt](https://github.com/CreativeMD/LittleTiles/files/3483771/crash-2019-08-08_23.27.40-client.txt)

**Comment by CreativeMD** [comment] 2019-08-10 17:04
No idea to be honest :( I can't see any issue caused by my mod. Also don't know which mod could cause it. Maybe you can do some test (remove some mods and see if it still happens)?

**Comment by Tschipp** [comment] 2019-08-12 09:45
Yeah I know, it's difficult to say... I have so many mods that mess with rendering and I'm just gonna hope that the issue goes away if I update some of them...

**Comment by CreativeMD** [comment] 2019-08-13 10:01
I'm not sure if this is rendering related.

**Comment by CreativeMD** [comment] 2019-09-29 15:25
Fixed in the newest pre-release.

**Closed as completed by CreativeMD** 2019-09-29 15:25 UTC
Labels: Bug
