### ISSUE TITLE
Crash with 1.4.8 for 1.11.2

### ISSUE THREAD

**Issue by sweetsosweet** [CreativeMD/LittleTiles#42] opened 2017-04-24 23:52 UTC
I'm getting this super weird crash ever since updating. I've downgraded to 1.4.7 and don't have this crash anymore. I'm using CreativeCore v1.7.3 for both.  Here's the report:

[https://pastebin.com/f5bbkyiP](https://pastebin.com/f5bbkyiP)

**Comment by CreativeMD** [comment] 2017-04-25 21:38
It's caused by BetterFoliage mod. I will try to fix it tomorrow. There were no issues with v2.1.3 if you want to  fix it temporarily.

**Comment by sweetsosweet** [comment] 2017-04-25 22:31
Oh ok, thank you! I'll downgrade Better Foliage instead then.

**Comment by Alaberti** [comment] 2017-05-05 03:18
I just wanted to note, on the off chance you weren't aware, this also affects the 1.10.2 version.

**Comment by ghost** [comment] 2017-05-15 09:33
This crash still occurs with 1.4.11 for 1.10.2:

[crash-2017-05-15_11.19.57-client.txt](https://github.com/CreativeMD/LittleTiles/files/1000656/crash-2017-05-15_11.19.57-client.txt)

I downgraded Better Foliage to 2.1.3, this works, but it should not be the solution...

**Comment by CreativeMD** [comment] 2017-05-15 10:11
Yes i know, i will try to fix it this week.

**Comment by CreativeMD** [comment] 2017-05-22 18:52
It will be fixed in the upcoming update 1.4.12 later this week.

**Comment by CreativeMD** [comment] 2017-05-31 11:12
Fixed in v1.4.12.

**Closed as completed by CreativeMD** 2017-05-31 11:12 UTC
