### ISSUE TITLE
Preview of Advanced Door is broken

### ISSUE THREAD

**Issue by Mrbysco** [CreativeMD/LittleTiles#346] opened 2020-02-22 16:57 UTC
## Client Info
* Minecraft Version: 1.12.2

* Forge Version: 14.23.5.2847
* Mod Version: v1.5.0-pre198
* Java Version: 1.8.0.232 (64 Bit)

## Issue Description
Currently the preview window of the Advanced Door does not work.

## Reproduce Steps
Create a Little Tile, Open the configure tool and select "Advanced Door".
You'll be greeted with a blank preview window.
Even when setting the axis properly and save it still shows blank.

<details>
  <summary>Screenshots</summary>
Screenshot of another Door setting:  

![Sliding Door](https://user-images.githubusercontent.com/9308260/75096117-ab92b880-559c-11ea-9d4f-4d1c896b09d2.png)  

Screenshot of Advanced Door setting:

![Advanced Door](https://user-images.githubusercontent.com/9308260/75096118-ac2b4f00-559c-11ea-894d-cb01a8426a0d.png)  

Screenshot of Advanced Door - Axis setting:

![Advanced Door - Axis](https://user-images.githubusercontent.com/9308260/75096119-acc3e580-559c-11ea-89d7-0d889947276a.png)  
</details>

**Comment by kirokadura** [comment] 2020-02-24 03:53
Can you test out the pre199_13 version on the Releases channel on our Discord? https://discord.gg/wExXDt

**Comment by CreativeMD** [comment] 2020-02-24 10:17
Newest unoffical versions

LittleTiles https://cdn.discordapp.com/attachments/326729168266199040/676913521866571796/LittleTiles_v1.5.0-pre199_13_mc1.12.2.jar
CreativeCore https://cdn.discordapp.com/attachments/326729168266199040/674237457612537876/CreativeCore_v1.9.91_mc1.12.2.jar
OnlinePictureFrame https://cdn.discordapp.com/attachments/326729168266199040/670229596406415370/OnlinePicFrame_v1.4.34_mc1.12.2.jar

**Comment by Mrbysco** [comment] 2020-02-26 15:54
Still have the same issue with the newest unofficial version.

**Comment by CreativeMD** [comment] 2020-02-29 13:14
Can you send me your structure, so I can reproduce this?

**Comment by CreativeMD** [comment] 2020-03-10 10:52
No matter what I do, I can't reproduce this issue. Pretty sure it's caused by the structure itself (maybe a weird edge case).

**Comment by CreativeMD** [comment] 2020-03-15 09:38
I will close this issue for now. Open a new issue with the structure if this issue still persists.

**Closed as completed by CreativeMD** 2020-03-15 09:38 UTC
