### ISSUE TITLE
when clicking on LT stuff with a block (to place it next to LT stuff) it overwrites LT stuff part

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#116] opened 2018-08-12 17:42 UTC
Using pre104 in 1.12.2

**Comment by ghost** [comment] 2018-08-12 17:44
This happens not always but sometimes. For example, once i created a sphere with chisel, and tried to place a block on it - it happend, then tried to place again and again - same.

**Comment by CreativeMD** [comment] 2018-08-12 17:45
Can you send me a screenshot of it?

**Comment by ghost** [comment] 2018-08-12 18:05
![2018-08-12_20 59 57](https://user-images.githubusercontent.com/32820765/44004888-03676e6c-9e73-11e8-9d8d-a7dd685598e0.png)
Right here i simulated the result using MCEdit (deleted LT tileentity block), But it looks same when it really happens. Also i remember that this happend before Layered grids were added (but I'm not fully sure)

**Comment by CreativeMD** [comment] 2018-08-12 18:19
![2018-08-12_20 18 38](https://user-images.githubusercontent.com/1353495/44005038-eed94836-9e6c-11e8-8713-f2e8eb0a4e8e.png)
To be honest I don't get what you mean.

**Comment by ghost** [comment] 2018-08-12 19:03
It doesnt happens always, just sometimes (when i went to reproduce it for a screenshot I couldnt do it, blocks I tried to place was placed normally as on your screenshot so i simulated it to show how it looks when it really happens)

**Comment by CreativeMD** [comment] 2018-08-12 21:12
I doubt that it is possible to be honest. I'm pretty sure something else is causing it, because you can't replace these blocks. Maybe only the client "thought" they would exist, but there was nothing for the server (so the block was placed and updated on client side). Therefore I would call it a synchronization issue.

How often did it happen?

**Comment by ghost** [comment] 2018-08-13 13:54
I dont have much free time those months, so I didnt use LT often but I believe this happens in 5-15% cases.

**Comment by CreativeMD** [comment] 2018-08-13 15:03
I will close the issue for now, because I cannot reproduce it, if it happens again, make a screenshot save the world and send it to me. Also try to log out and log in again to see if it was just a synchronization issue.

**Closed as completed by CreativeMD** 2018-08-13 15:03 UTC
