### ISSUE TITLE
Multiplayer crash in modpack

### ISSUE THREAD

**Issue by Saereth** [CreativeMD/LittleTiles#438] opened 2020-07-05 15:11 UTC
Looks like Entity being cast to EntityMP. This was reported by a player from the interactions 2.0 modpack while trying to access the gui on an advanced rocketry block. I havent reported this to advanced rocketry yet because it looks like its on your end but if not let me know and I'll pass it on to him.

here is the crashlog, this is reproducible:
https://paste.feed-the-beast.com/view/f67e29dc#L47

CreativeCore_v1.10.16_mc1.12.2.jar
LittleTiles_v1.5.0-pre199_34_mc1.12.2.jar
Forge: 14.23.5.2847

**Comment by CreativeMD** [comment] 2020-07-06 07:11
Duplicate of https://github.com/CreativeMD/CreativeCore/issues/75, this will be fixed in the next release which should be there in 1-2 weeks.

**Closed as completed by CreativeMD** 2020-07-06 07:11 UTC
