### ISSUE TITLE
[Bug] Server crash when creating angled pieces

### ISSUE THREAD

**Issue by Captainaviator** [CreativeMD/LittleTiles#89] opened 2018-05-28 14:26 UTC
Mod calls a GUI class server-side when it throws an error.  This cannot be interacted with from the server, causing it to crash.  I'm unable to see what this error was.

**Comment by CreativeMD** [comment] 2018-05-28 14:30
I really need the crash log (server log). Otherwise I can't do anything about it.

**Comment by ghost** [comment] 2018-05-28 14:32
Hmmm... I guess it's related
https://github.com/CreativeMD/LittleTiles/issues/87

**Comment by CreativeMD** [comment] 2018-05-28 14:33
He didn't say anything about the replay mod.

**Comment by An-Sar** [comment] 2018-05-29 23:47
The server crash was actually being caused by VanillaFix calling a clientside gui class in response to this:

```
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_162]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_162]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_162]
        at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_162]
        at com.creativemd.littletiles.common.action.LittleAction.getIngredientsPreviews(LittleAction.java:710) ~[LittleAction.class:?]
        at com.creativemd.littletiles.common.action.LittleAction.addTilesToInventoryOrDrop(LittleAction.java:719) ~[LittleAction.class:?]
        at com.creativemd.littletiles.common.action.block.LittleActionPlaceRelative.placeTile(LittleActionPlaceRelative.java:194) ~[LittleActionPlaceRelative.class:?]
        at com.creativemd.littletiles.common.action.block.LittleActionPlaceRelative.action(LittleActionPlaceRelative.java:118) ~[LittleActionPlaceRelative.class:?]
        at com.creativemd.littletiles.common.action.LittleAction.executeServer(LittleAction.java:208) ~[LittleAction.class:?]
        at com.creativemd.creativecore.common.packet.PacketReciever$2.run(PacketReciever.java:129) ~[PacketReciever$2.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_162]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_162]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
```

**Comment by CreativeMD** [comment] 2018-05-30 10:09
Can you send me a screenshot of what you are doing, so I can reproduce it?

**Comment by CreativeMD** [comment] 2018-06-05 14:42
This issue should be fixed in the next pre-release (hopefully).

**Closed as completed by CreativeMD** 2018-06-05 14:42 UTC
