### ISSUE TITLE
 Invisible door

### ISSUE THREAD

**Issue by RPJOF** [CreativeMD/LittleTiles#374] opened 2020-04-12 09:41 UTC
Hello, I have a huge problem with the renderings of my doors. The animation goes well but as soon as it returns to their basic position, they disappear. They are still there but we don't see them!
Here is my info:
JAVA: 14.23.5.2847
Little-tiles:
1.12.2 Pre 199_19
Creative Core:
V1.10.10
Screen of my mods and the bug:
Have a good day!
(I use the command "lt-open" to open my doors! and sorry for my bad english)
![2020-04-11_21 05 00](https://user-images.githubusercontent.com/60546959/79065671-78be9400-7cb2-11ea-8a7f-ba44932342ea.png)
![2020-04-11_21 05 10](https://user-images.githubusercontent.com/60546959/79065675-7b20ee00-7cb2-11ea-8e9c-a0f36d54c053.png)
![Capture](https://user-images.githubusercontent.com/60546959/79065683-8bd16400-7cb2-11ea-8169-5e8a91b8911c.PNG)

**Comment by CreativeMD** [comment] 2020-04-12 09:43
Saw your post already, but didn't have the time answer. Can you export the structure and send it to me so I can test it myself?

**Comment by RPJOF** [comment] 2020-04-12 09:45
> J'ai déjà vu votre message, mais je n'ai pas eu le temps de répondre. Pouvez-vous exporter la structure et me l'envoyer pour que je puisse la tester moi-même?

What do you mean ? Send the map? (Sorry I did not understand)

**Comment by CreativeMD** [comment] 2020-04-12 09:50
https://www.youtube.com/watch?v=u1vfdr_jdbA

You can also send the map if it's too complicated for you.

**Comment by CreativeMD** [comment] 2020-04-12 09:51
https://www.youtube.com/watch?v=u1vfdr_jdbA

You can also send the map if it's too complicated for you.

**Comment by RPJOF** [comment] 2020-04-12 09:54
{tiles:[{boxes:[[I;13,16,64,16,32,80],[I;13,48,80,16,64,96],[I;13,16,32,16,32,48],[I;13,80,96,16,96,112],[I;13,16,96,16,32,112],[I;13,112,48,16,128,64],[I;13,80,0,16,96,16],[I;13,144,64,16,160,80],[I;13,112,16,16,128,32],[I;13,176,80,16,192,96],[I;13,144,32,16,160,48],[I;13,48,48,16,64,64],[I;13,16,0,16,32,16],[I;13,80,64,16,96,80],[I;13,48,16,16,64,32],[I;13,112,80,16,128,96],[I;13,80,32,16,96,48],[I;13,144,96,16,160,112],[I;13,176,48,16,192,64],[I;13,144,0,16,160,16],[I;13,176,16,16,192,32],[I;13,0,64,16,16,80],[I;13,32,80,16,48,96],[I;13,0,32,16,16,48],[I;13,64,96,16,80,112],[I;13,32,48,16,48,64],[I;13,0,96,16,16,112],[I;13,64,0,16,80,16],[I;13,128,64,16,144,80],[I;13,96,16,16,112,32],[I;13,160,80,16,176,96],[I;13,128,32,16,144,48],[I;13,160,48,16,176,64],[I;13,0,0,16,16,16],[I;13,64,64,16,80,80],[I;13,32,16,16,48,32],[I;13,96,80,16,112,96],[I;13,128,96,16,144,112],[I;13,64,32,16,80,48],[I;13,96,48,16,112,64],[I;13,128,0,16,144,16],[I;13,160,16,16,176,32],[I;13,16,80,16,32,96],[I;13,48,96,16,64,112],[I;13,16,48,16,32,64],[I;13,48,64,16,64,80],[I;13,80,16,16,96,32],[I;13,144,80,16,160,96],[I;13,112,32,16,128,48],[I;13,176,96,16,192,112],[I;13,144,48,16,160,64],[I;13,112,0,16,128,16],[I;13,176,64,16,192,80],[I;13,16,16,16,32,32],[I;13,80,80,16,96,96],[I;13,48,32,16,64,48],[I;13,112,96,16,128,112],[I;13,80,48,16,96,64],[I;13,48,0,16,64,16],[I;13,112,64,16,128,80],[I;13,144,16,16,160,32],[I;13,176,32,16,192,48],[I;13,176,0,16,192,16],[I;13,32,96,16,48,112],[I;13,0,48,16,16,64],[I;13,32,64,16,48,80],[I;13,0,16,16,16,32],[I;13,64,80,16,80,96],[I;13,0,80,16,16,96],[I;13,96,32,16,112,48],[I;13,160,96,16,176,112],[I;13,128,48,16,144,64],[I;13,96,0,16,112,16],[I;13,160,64,16,176,80],[I;13,128,16,16,144,32],[I;13,32,32,16,48,48],[I;13,96,96,16,112,112],[I;13,64,48,16,80,64],[I;13,32,0,16,48,16],[I;13,96,64,16,112,80],[I;13,64,16,16,80,32],[I;13,128,80,16,144,96],[I;13,160,32,16,176,48],[I;13,160,0,16,176,16]],tile:{block:"minecraft:wool:14"}}],min:[I;13,0,0],size:[I;3,192,112],display:{Name:"Rideau"},count:84,structure:{duration:270,interpolation:0,distance:192,name:"Rideau",activateParent:0b,id:"slidingDoor",events:[],disableRightClick:0b,direction:1}}

**Comment by RPJOF** [comment] 2020-04-12 10:00
I have several curtain models

**Comment by CreativeMD** [comment] 2020-04-12 10:17
Ok, it might be better if you could send me your world. Because the door works absolutely fine for me.

**Comment by RPJOF** [comment] 2020-04-12 10:33
Ok, here is the map, if you can, try to use the mods, because that's how I open them

[[MAP](http://meteoff.cf/dev/Concert_arena.zip)]

**Comment by CreativeMD** [comment] 2020-04-13 08:30
Where do I activate them? I tried every single button/ lever, but I can't find it.

**Comment by RPJOF** [comment] 2020-04-13 08:37
It's right in front of the stage, on the quartz wall, there is a button with a panel written "OUVERTURE RIDEAU SCENE" and "click here" at the top, but did you use the mods that were in the folder?  (Sorry I can't show you a photo now I have no electricity 😬)

**Comment by CreativeMD** [comment] 2020-04-13 10:43
Do I need the mods in order for the button to work?

**Comment by RPJOF** [comment] 2020-04-13 10:45
Yes, just from Wireless Redstone and its Add-On (and LittleTiles too)!

**Comment by CreativeMD** [comment] 2020-04-13 10:57
Ok is there way to do it without them? What does the button actually do? Just happens all doors?

**Comment by RPJOF** [comment] 2020-04-13 11:11
this triggers control blocks which are placed on the roof! they are right above the place where there are all the buttons

**Comment by RPJOF** [comment] 2020-04-13 19:16
-572 38 -298

**Comment by CreativeMD** [comment] 2020-04-13 20:14
I have tested it already and could reproduce the issue. I will investigate it further. Let's hope I can fix it.

**Comment by RPJOF** [comment] 2020-04-13 20:38
Ok! Thank you very much, despite this bug, the mod remains great!

**Comment by CreativeMD** [comment] 2020-04-26 21:43
This issue should be fixed in the newest version. If not make sure to tell me so (and I will reopen the issue).

**Closed as completed by CreativeMD** 2020-04-26 21:43 UTC

**Comment by RPJOF** [comment] 2020-04-27 08:20
Yes it's settled! Thank you so much! Nice day
