### ISSUE TITLE
harvestLevelBlock has no effect

### ISSUE THREAD

**Issue by LemADEC** [CreativeMD/LittleTiles#675] opened 2021-05-14 10:16 UTC
As reported initially in https://github.com/CreativeMD/LittleTiles/issues/609, the harvestLevelBlock has no visible effect.

Steps to reproduce:
1- start a new single player world with just LittleTiles_v1.5.8_mc1.12.2 + CreativeCore_v1.10.58_mc1.12.2, no other mods
2- use /cmdconfig to set survival settings as such:
```
  "survival": {
    "limitAffectedBlocks": true,
    "maxAffectedBlocks": 2,
    "harvestLevelBlock": 0,
    "editUnbreakable": false,
    "minimumTransparency": 255,
    "limitEditBlocks": true,
    "maxEditBlocks": 10,
    "limitPlaceBlocks": true,
    "maxPlaceBlocks": 10
  },
```
3- place a few obsidian, stone and diamond ore blocks, grab a little hammer
4- switch to survival
5- switch Little hammer to type or box mode then try to chisel
* 1 stone can be chiseled => ok
* 2 stone can be chiseled => ok
* 3 stones can't be chiseled (affected blocks limit reach) => ok
* 1 obsidian can be modified => NOK
* 1 diamond ore can be modified => NOK

I suspect the issue is related to the condition which return too soon when editUnbreakable is false, here:
https://github.com/CreativeMD/LittleTiles/blob/c21643eb665d4340cfc0ae05b7feb237291808b2/src/main/java/com/creativemd/littletiles/common/action/LittleAction.java#L339

**Comment by CreativeMD** [comment] 2021-05-14 13:32
Good call! Thanks a lot, could never reproduce this issue because editUnbreakable was set to true. Fixed in the newest version!

**Closed as completed by CreativeMD** 2021-05-14 13:32 UTC
