### ISSUE TITLE
[1.12.2] Weird behaviour with Replace Mode

### ISSUE THREAD

**Issue by kirokadura** [CreativeMD/LittleTiles#86] opened 2018-05-06 19:47 UTC
LT version: pre97
Core version: 1.9.22
Forge Version: 14.23.0.2515

Say I want to put this 32x32x1 (heigh x width x depht) wallpaper I made:

![2018-05-06_16 24 13](https://user-images.githubusercontent.com/29471180/39677115-2c81ef62-514c-11e8-93ab-a55b02eb2d30.png)

Over this orange wool block using the Replace mode:

![2018-05-06_16 23 02](https://user-images.githubusercontent.com/29471180/39677120-405d5490-514c-11e8-8989-8143876ba4f4.png)

When replacing it, this happens:

![2018-05-06_16 23 43](https://user-images.githubusercontent.com/29471180/39677126-545f6c30-514c-11e8-9f92-dc065c082217.png)

If I try to break it this happens:

![glitch replace mode](https://user-images.githubusercontent.com/29471180/39677139-7e4909a2-514c-11e8-857d-24581b53fd64.gif)

Doing the same with a 32x32x1 thick layer of stone does not wield this strange bug:

![2018-05-06_16 30 57](https://user-images.githubusercontent.com/29471180/39677151-9dbf6132-514c-11e8-968f-2308c4b249a2.png)

But I if I try with this one:

Before placing:

![2018-05-06_16 34 57](https://user-images.githubusercontent.com/29471180/39677157-bbddc992-514c-11e8-84c9-e560fba13c3a.png)

After placing:

![2018-05-06_16 31 31](https://user-images.githubusercontent.com/29471180/39677160-c322243c-514c-11e8-8d40-a0a2bde3b79a.png)

It happens in 16 grid size too. It seems that there are multiple tiles on the same space.

**Comment by Dushess** [comment] 2018-05-07 21:06
Not fully in theme, but with my 92nd+ build i seen same random slicing to more tiles. Caused by updating LT block by cutting and undoing, not used replace mode, no tiles overlap. Just similar effect, may be related.

**Comment by CreativeMD** [comment] 2018-05-26 09:21
Fixed it, will be in the next pre-release. Thanks for reporting this issue was really easy to reproduce.

**Closed as completed by CreativeMD** 2018-05-26 09:21 UTC
