### ISSUE TITLE
Kicked From Server

### ISSUE THREAD

**Issue by Thorandan** [CreativeMD/LittleTiles#119] opened 2018-08-29 18:11 UTC
I  attempted to place an entire building constructed from little tiles as one fixed structure and was kicked from the server with the message: "Internal Exception: java.lang.IllegalArgumentException: Payload may not be larger that=n 32767 bytes".
 I now cannot reconnect, as whenever I try I get the same issue. I am also  told that nothing appears in the server console during this.

**Comment by CreativeMD** [comment] 2018-08-29 21:32
You probably use an old version of LT. Probably for 1.7.10 or 1.10.2. It is fixed in 1.5.0 (which is available for 1.11.2 and 1.12.2). Sorry but I don't support these versions anymore :(. I recommend to either update to newer versions or fix the problem using MCEdit (delete the placed blocks). Sorry :/

**Comment by Thorandan** [comment] 2018-08-29 21:44
LittleTiles  is v1.5.0-pre105_mc1.12.2.jar

**Comment by ProsperCraft** [comment] 2018-08-31 11:51
https://www.dropbox.com/s/t9geaz880gy0f8u/littletiles.zip?dl=1

World files

Download Ancient TownCraft with the twitch launcher
unzip that folder in to your saves folder
load in to that world, and open to lan enable creative and cheats
go through the green portal there which then puts you in the overworld
type /tp 5593 69 -26
walk outside and look at that barn where the tree farm is

resulting kick.
https://gist.github.com/ProsperCraft/b34a2fece7058d2a5b012486714724ab

**Comment by CreativeMD** [comment] 2018-09-03 12:07
I could get the structure from the inventory of a player:
![](https://i.imgur.com/pQQpKHm.png)

There was no issue at all. I tested it without any other mod installed, so I'm pretty sure it this issue only occurs if other mods are installed. So maybe it's because of certain blocks you use (what kind of blocks did you use for the structure?) or a mod is doing something weird.

Can you try to remove certain mods from the pack until only LT is installed and see if it still occurs? Through that way you can find out which mod is causing the trouble.

**Comment by CreativeMD** [comment] 2018-09-10 20:47
Any updates?

**Comment by ProsperCraft** [comment] 2018-09-11 00:38
Poking Thor to see if he can do the testing.

**Comment by CreativeMD** [comment] 2018-09-11 08:45
A guy on discord had the same issue and it looks like the issue is caused by "The One Probe". Once you look at the structure it tries to send the tooltip to the client and crashes because the structure is too large. I contacted the author, maybe it will be fixed.

**Closed as completed by CreativeMD** 2018-09-11 08:45 UTC
