### ISSUE TITLE
Glitching door parts and duplication (singleplayer)

### ISSUE THREAD

**Issue by juh9870** [CreativeMD/LittleTiles#783] opened 2021-11-05 13:26 UTC
Upon opening and closing this door, I'm frequently getting bugged parts sticking out
https://pastebin.com/xvaEDV3e
![2021-11-05_15 23 45](https://user-images.githubusercontent.com/15922601/140517331-2c9083da-ceb3-4c78-bf23-17fed07ea066.png)
![2021-11-05_15 23 20](https://user-images.githubusercontent.com/15922601/140517336-e177d29b-92b7-4fb5-b6da-7a225f46e2ec.png)
![2021-11-05_15 23 24](https://user-images.githubusercontent.com/15922601/140517337-a151f96e-318c-408d-93a4-f70bb8a64fa6.png)
![2021-11-05_15 23 30](https://user-images.githubusercontent.com/15922601/140517338-5c9ee9ce-13fa-4e51-84a3-1f7132f296da.png)
![2021-11-05_15 23 38](https://user-images.githubusercontent.com/15922601/140517341-52991726-c447-4237-aa48-6537677bc826.png)

**Comment by CreativeMD** [comment] 2021-11-05 14:48
Duplicate off https://github.com/CreativeMD/LittleTiles/issues/605

**Closed as completed by CreativeMD** 2021-11-05 14:48 UTC
