### ISSUE TITLE
Some blocks are missing when pasting

### ISSUE THREAD

**Issue by Potsukin** [CreativeMD/LittleTiles#524] opened 2020-11-01 10:44 UTC
Sometimes some blocks are missing when pasting

https://youtu.be/meCLlK05ToQ

**Comment by CreativeMD** [comment] 2020-11-03 10:11
I could not reproduce it. Maybe try out the newest version and see if it's fixed. If not I really need the structure you used.

**Comment by Potsukin** [comment] 2020-11-03 10:29
Going to try new version, thanks

**Comment by CreativeMD** [comment] 2020-11-12 23:43
Any news on this?

**Comment by Potsukin** [comment] 2020-11-18 00:03
This seems to happen with dence chunks (many blocks including slices).

**Comment by CreativeMD** [comment] 2020-11-18 08:24
Can you record another video? I really need to know the exact circumstances in order to reproduce it.

**Comment by Potsukin** [comment] 2020-11-19 01:05
https://youtu.be/sHYtqAr3qGE

Here is a video. It may look like a different issue, but I think the cause is the same.
 I was changed to a different block with the glove, some blocks disappeared (removed) before I knew it, and reloading the chunk did not fix it.

**Comment by Potsukin** [comment] 2020-11-19 09:45
Another picture. Some slice blocks were lost - slice block only
![2020-11-19_bug](https://user-images.githubusercontent.com/11745850/99649187-399dc000-2a97-11eb-8f8f-7f36b233570b.jpg)

**Comment by CreativeMD** [comment] 2020-11-23 09:32
Can you export the structure before placing it? I also need the structure you placed it against.

**Comment by CreativeMD** [comment] 2020-12-03 19:19
I could some of the issues, not sure if all of them. We shall see when the new version is coming out.

**Comment by CreativeMD** [comment] 2021-01-10 23:38
Should be fixed in the newest version.

**Closed as completed by CreativeMD** 2021-01-10 23:38 UTC
