### ISSUE TITLE
Sliding door duplicates if the signal applied to the door activator is too short.

### ISSUE THREAD

**Issue by oniison** [CreativeMD/LittleTiles#766] opened 2021-10-21 09:44 UTC
The door and the noclip pressure plate was made using C&B. Sometimes when you left click it breaks the entire thing (as shown), and sometimes leaves two open doors which result in "Structure is not loaded" when left clicked on
![sliding door duplicates](https://user-images.githubusercontent.com/67521187/138253034-783fee73-c815-4547-b8b6-cd6fc491c5f0.gif)
upd: tested on a server, if that matters
upd2: issue still remains if everything is remade with littletiles instead of C&B

**Comment by CreativeMD** [comment] 2021-10-25 08:00
Can you export the door to here so I can test it myself?

**Comment by CreativeMD** [comment] 2021-11-05 09:48
Make the doors stay animated, that should hopefully fix your issue. Will close it for now. As it's a duplicate of https://github.com/CreativeMD/LittleTiles/issues/605

**Closed as completed by CreativeMD** 2021-11-05 09:48 UTC
