### ISSUE TITLE
Crash with removing blocks from little bag

### ISSUE THREAD

**Issue by Tschipp** [CreativeMD/LittleTiles#345] opened 2020-02-17 17:46 UTC
Got this crash log:
https://paste.dimdev.org/usihojeziy.mccrash

The bits being removed from the bag were regular cobblestone bits.
After reentering the world, the bits were in the inventory, so they had been removed but it crashed nevertheless

LT pre 198
CC 1.9.90

**Comment by CreativeMD** [comment] 2020-02-17 18:04
This issue has been fixed already in pre199 which is not officially released yet (due to an issue with dynamic surroundings). 

https://cdn.discordapp.com/attachments/326729168266199040/674237457612537876/CreativeCore_v1.9.91_mc1.12.2.jar
https://cdn.discordapp.com/attachments/326729168266199040/676913521866571796/LittleTiles_v1.5.0-pre199_13_mc1.12.2.jar

**Comment by Tschipp** [comment] 2020-02-17 18:54
Nice, thanks

**Comment by TheMightyAtomNL** [comment] 2020-02-20 23:55
After updating to the versions linked above, I'm getting an exception on game startup:

_java.lang.NoClassDefFoundError: com/creativemd/littletiles/common/utils/ingredients/rules/BlockIngredientRule_

_Caused by: java.lang.ClassNotFoundException: com.creativemd.littletiles.common.utils.ingredients.rules.BlockIngredientRule_

_Caused by: java.lang.NullPointerException_

(I left out all the stacktrace crap)

I wanted to try out these unreleased builds anyway because of the bug when tiles don't load and become invisible whenever a chunk loads in, as described by Nonsanity in the other thread.

I'm not using Dynamic Surroundings so I guess I'm good there.

**Comment by CreativeMD** [comment] 2020-02-21 09:41
LTPhoto has been updated to the newest version yet.

**Comment by TheMightyAtomNL** [comment] 2020-02-21 18:29
Not sure what you mean by that, what's LTPhoto?

**Comment by CreativeMD** [comment] 2020-02-22 08:51
I meant has not been updated yet. Would be more helpful if you could post the entire crash. Nonetheless this looks very similar to another crash which was caused by LTPhoto (an addon for LT).

**Comment by TheMightyAtomNL** [comment] 2020-02-22 14:39
So guess you meant to say _"LTPhoto **hasn't** been updated to the newest version yet."_
Also, I'm not using LTPhoto so I don't think that LTP is the problem.

Here's my full crash log: https://paste.dimdev.org/owijoxivaq.rb

**Comment by CreativeMD** [comment] 2020-02-22 15:39
Oh right it's OnlinePictureFrame:

https://cdn.discordapp.com/attachments/326729168266199040/670229596406415370/OnlinePicFrame_v1.4.34_mc1.12.2.jar

**Comment by TheMightyAtomNL** [comment] 2020-02-23 02:46
That fixed it though but now upon entering my world the game crashes with this exception:
https://paste.dimdev.org/zumirokoji.http

I hope all my LittleTiles structures are still compatible, or else I'm screwed.

**Comment by CreativeMD** [comment] 2020-02-23 16:13
That one "should" be fixed.

**Comment by TheMightyAtomNL** [comment] 2020-02-23 16:19
Great. :) Can I test it?

**Comment by CreativeMD** [comment] 2020-02-23 16:34
You already have the newest version.

**Comment by TheMightyAtomNL** [comment] 2020-02-23 16:41
Let me try entering my world again...
Ok it's not very stable, it still seems to crash every now and then and VanillaFix blames LittleTiles.

Also now the server is constantly timing me out every single time. Can't do anything, though this probably unelated to LittleTiles. I had the problem once before and the only fix was to format my C drive and reinstall Windows. Yeah.

**Comment by CreativeMD** [comment] 2020-03-08 17:55
The new version is out, this issue should be fixed now.

**Closed as completed by CreativeMD** 2020-03-08 17:55 UTC
