### ISSUE TITLE
Crashed for Unknown Reason, Suggested LittleTiles, NullPointerException

### ISSUE THREAD

**Issue by TechTastic** [CreativeMD/LittleTiles#551] opened 2020-12-31 00:53 UTC
[crash-2020-12-30_18.50.05-client.txt](https://github.com/CreativeMD/LittleTiles/files/5756128/crash-2020-12-30_18.50.05-client.txt)

I was moving away from the only area with LittleTiles structures

Happened on Client, server seemed to be unaffected

New Crash Log: 
[crash-2020-12-30_19.24.07-client.txt](https://github.com/CreativeMD/LittleTiles/files/5756184/crash-2020-12-30_19.24.07-client.txt)

Server Log of both events: 
[latest.log](https://github.com/CreativeMD/LittleTiles/files/5756186/latest.log)

**Comment by CreativeMD** [comment] 2021-01-01 14:06
Duplicate of https://github.com/CreativeMD/LittleTiles/issues/541

**Closed as completed by CreativeMD** 2021-01-01 14:06 UTC
