### ISSUE TITLE
Duplication bug

### ISSUE THREAD

**Issue by darkphan** [CreativeMD/LittleTiles#43] opened 2017-04-28 04:26 UTC
With LittleTiles version 1.4.8 when you break any little tiles the tiles are duped. If you happen to break a little tiles storage with items in it, it dupes the little tiles storage and the items in it.

EDIT: This happens when you break LittleTiles blocks with a pick or some other tool. Using the LittleTiles hammer seems to only drop one block

**Comment by CreativeMD** [comment] 2017-04-29 19:08
Could you give me some further information. Could not reproduce this bug. Maybe share some screenshots. What versions do you use (mod version, forge version)?

**Comment by darkphan** [comment] 2017-04-29 19:25
Using Forge 13.20.0.2285, LittleTiles version 1.4.8. This is on 1.11.2 of Minecraft. Basically use the hammer to make blocks into the little tiles blocks (i did 16x16x16 in the hammer) place those blocks down and then break those blocks with a vanilla pickaxe and you get 2 blocks when you break the block.

**Comment by CreativeMD** [comment] 2017-04-30 11:21
Does this fixes it?
https://www.dropbox.com/s/g60w809m0658ygm/LittleTiles%20v1.4.9%20mc1.11.2.jar?dl=1

**Comment by BSKCorp** [comment] 2017-04-30 15:38
Got a crash when opening the hammer GUI to test (hope you don't mind the help) did this 3 times to verify.

Crash Log - https://pastebin.com/tP0VFAm8 

Full Log - 
[crash-2017-04-30_10.38.00-client.txt](https://github.com/CreativeMD/LittleTiles/files/966810/crash-2017-04-30_10.38.00-client.txt)

**Comment by CreativeMD** [comment] 2017-04-30 15:55
Could you try to use the newest CreativeCore version 1.7.4?

**Comment by BSKCorp** [comment] 2017-04-30 16:31
I would if I knew where to get it lol I don't see it on curse forge or MC forums. I can compile your latest build if ya like, take me a while though I would have to reset everything back up due to the new OS install I just did.

**Comment by BSKCorp** [comment] 2017-04-30 16:36
You had me looking all over the place for 1.7.4 then I realized I was using 7.2 lol

Edit - Bug fixed, sorry for the oversight.

**Comment by darkphan** [comment] 2017-04-30 19:18
Yes, this LittleTiles resolves the issue.

**Comment by CreativeMD** [comment] 2017-05-01 13:21
It is fixed in v1.4.9 (will be available soon).

**Closed as completed by CreativeMD** 2017-05-01 13:21 UTC
