### ISSUE TITLE
Shadowing issue

### ISSUE THREAD

**Issue by beefycomputer** [CreativeMD/LittleTiles#245] opened 2019-08-25 20:17 UTC
https://gfycat.com/frenchlinedgrouse black where no black should be.

**Comment by SlayerTheChikken** [comment] 2019-08-27 16:41
I think in general this is an issue with default minecraft lighting (I think even in vanilla I had this issue with slabs and stairs awhile back) and if it were to be fixed it may change the way mc lighting works.. I could be wrong tho :3

**Comment by CreativeMD** [comment] 2019-09-16 12:29
I can't reproduce this issue. Is optifine installed as well?

**Comment by beefycomputer** [comment] 2019-09-16 14:40
Yes, I do have optifine installed. The latest version for 1.12.2

**Comment by CreativeMD** [comment] 2019-09-16 14:41
Can you remove Optifine and see if it fixes the issue?

**Comment by CreativeMD** [comment] 2019-09-29 15:21
Have you tried it already?

**Comment by beefycomputer** [comment] 2019-09-29 16:07
> Have you tried it already?

sorry no. when I do I will tell you

**Comment by CreativeMD** [comment] 2020-08-28 19:54
Sorry this issue will not be fixed in 1.12. Let's hope things are better in 1.16.

**Closed as completed by CreativeMD** 2020-08-28 19:54 UTC
Labels: Bug
