### ISSUE TITLE
Mod Breaks Game Every time you Load A World

### ISSUE THREAD

**Issue by lordofpotatos** [CreativeMD/LittleTiles#622] opened 2021-04-03 05:18 UTC
![Capturepotato](https://user-images.githubusercontent.com/81840098/113469267-274a7000-9401-11eb-975b-9494b08d767e.JPG)
If you load a 1.12.2 world, with this mod your game will crash Please fix this glitch

**Comment by kirokadura** [comment] 2021-04-03 14:46
Please post the full crash-report file so we can know what the issue is.

**Comment by CreativeMD** [comment] 2021-04-09 09:20
Will close this issue for now. Most likely either your CreativeCore or LittleTiles version is outdated.

**Closed as completed by CreativeMD** 2021-04-09 09:20 UTC
