### ISSUE TITLE
Door set to "Stay entity" became unusable and can't be broken after server reboot

### ISSUE THREAD

**Issue by zFERDQFREZrzfq** [CreativeMD/LittleTiles#974] opened 2024-05-23 11:20 UTC
Hello,

While I was doing some tests with doors, I built a dooble-door with an activator frame and set both doors to "Stay as entity".
After a server reboot, I wanted to pick up the whole assembly to move it but the two doors stays in place and can't be picked up or interacted with.

The server runs :
- Minecraft 1.20.1
- Forge 47.2.32
- LittleTiles 1.6.0-pre103
- CreativeCore 2.11.28

Nothing happens when I try to break the door, even with the LittleWrench, and I get this error in the server log when I try to interact with the doors :

```
[23May2024 11:07:33.394] [Server thread/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class team/creative/littletiles/client/LittleTilesClient for invalid dist DEDICATED_SERVER
[23May2024 11:07:33.396] [Server thread/ERROR] [creativecore/]: Executing a packet ran into an exception
java.lang.RuntimeException: Attempted to load class team/creative/littletiles/client/LittleTilesClient for invalid dist DEDICATED_SERVER
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.20.1-47.2.32.jar%2369!/:1.0]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at team.creative.littletiles.common.structure.type.animation.LittleDoor.use(LittleDoor.java:115) ~[LittleTiles_BETA_v1.6.0-pre103_mc1.20.1.jar%23480!/:1.6.0-pre103]
	at team.creative.littletiles.common.action.LittleActionActivated.action(LittleActionActivated.java:31) ~[LittleTiles_BETA_v1.6.0-pre103_mc1.20.1.jar%23480!/:1.6.0-pre103]
	at team.creative.littletiles.common.action.LittleActionActivated.action(LittleActionActivated.java:16) ~[LittleTiles_BETA_v1.6.0-pre103_mc1.20.1.jar%23480!/:1.6.0-pre103]
	at team.creative.littletiles.common.action.LittleActionInteract.action(LittleActionInteract.java:123) ~[LittleTiles_BETA_v1.6.0-pre103_mc1.20.1.jar%23480!/:1.6.0-pre103]
	at team.creative.littletiles.common.action.LittleAction.executeServer(LittleAction.java:108) ~[LittleTiles_BETA_v1.6.0-pre103_mc1.20.1.jar%23480!/:1.6.0-pre103]
	at team.creative.creativecore.common.network.CreativePacket.execute(CreativePacket.java:14) ~[CreativeCore_FORGE_v2.11.28_mc1.20.1.jar%23401!/:2.11.28]
	at team.creative.creativecore.common.network.CreativeNetwork.lambda$registerType$2(CreativeNetwork.java:52) ~[CreativeCore_FORGE_v2.11.28_mc1.20.1.jar%23401!/:2.11.28]
	at net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:67) ~[server-1.20.1-20230612.114412-srg.jar%23587!/:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23587!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23587!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23587!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23587!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23587!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23587!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23587!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23587!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[server-1.20.1-20230612.114412-srg.jar%23587!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:732) ~[server-1.20.1-20230612.114412-srg.jar%23587!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[server-1.20.1-20230612.114412-srg.jar%23587!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23587!/:?]
	at java.lang.Thread.run(Thread.java:842) ~[?:?]
```

**Comment by zFERDQFREZrzfq** [comment] 2024-05-23 11:30
I could remove the bugged doors by using this command :
`/kill @e[limit=1,sort=nearest,type=littletiles:litte_animation]`

**Comment by CreativeMD** [comment] 2024-09-13 14:14
This issue has been fixed in the meantime. I could not reproduce it anymore. Again sorry for responding that late.

**Closed as completed by CreativeMD** 2024-09-13 14:14 UTC
