### ISSUE TITLE
Crash 1.12.2 Wrench GUI

### ISSUE THREAD

**Issue by jonabrv1965** [CreativeMD/LittleTiles#69] opened 2017-12-31 00:48 UTC
Hi, I was starting to play your mod, and found this glitch (occurs when tried to craft a storage in the wrench gui). Here the crash log : 
[crash-2017-12-30_19.24.25-client.txt](https://github.com/CreativeMD/LittleTiles/files/1594898/crash-2017-12-30_19.24.25-client.txt)

By the way, may I suggest to update the video in the curse page. Seems to be pretty old, and I had hard time to figure out all the features (i.e.: the hammer works very different in the 1.12.x version)

Thanks in advance!

**Comment by CreativeMD** [comment] 2018-01-01 14:18
Looks like it is caused by an empty recipe. It will be fixed in the upcoming version. Thanks for reporting this issue.
And yes, tutorials will be there soon. I know that it's a bit difficult to figure out how everything is working at the moment.

**Comment by CreativeMD** [comment] 2018-01-13 18:21
Is fixed now.

**Closed as completed by CreativeMD** 2018-01-13 18:21 UTC
