### ISSUE TITLE
Placing fixed structure that outputs number crashes

### ISSUE THREAD

**Issue by Doc-1** [CreativeMD/LittleTiles#689] opened 2021-05-23 17:40 UTC
I created a fixed structure with a signal output and assigned it to output a number. After placing a few of them down my game crashed. When I attempted to join the world again the game crashed with another error and I can no longer join the world.

The crash caused by placing the fixed structure.
[crash-2021-05-23_12.30.42-server.txt](https://github.com/CreativeMD/LittleTiles/files/6528604/crash-2021-05-23_12.30.42-server.txt)

The crash caused by joining the world.
[crash-2021-05-23_13.33.36-server.txt](https://github.com/CreativeMD/LittleTiles/files/6528605/crash-2021-05-23_13.33.36-server.txt)

**Comment by CreativeMD** [comment] 2021-05-24 08:41
Can you test if the newest commit fixes it?

**Comment by CreativeMD** [comment] 2021-05-27 10:06
Any news?

**Comment by Doc-1** [comment] 2021-05-27 22:20
Sorry, I don't regularly check my email or GitHub. Best to notify me on Discord then I can respond here.
But it still occurs. There doesn't seem to be a min or max number of times you have to place it to occur.

**Comment by CreativeMD** [comment] 2021-06-14 09:55
Can you try out the newest version? There have been a few fixes in that regard. If it still crashes can you post the new crash-report?

**Comment by Doc-1** [comment] 2021-06-14 23:58
Still occurs. But, something additional I've realized is that Undoing and then placing a new one down is when it is triggered.

[crash-2021-06-14_19.56.28-server.txt](https://github.com/CreativeMD/LittleTiles/files/6651847/crash-2021-06-14_19.56.28-server.txt)

**Comment by CreativeMD** [comment] 2021-07-20 09:33
Fixed in the newest version. It was caused by queueing a ticket with zero delay, which resulted in a negative delay.

**Closed as completed by CreativeMD** 2021-07-20 09:33 UTC
