### ISSUE TITLE
[1.20.1] Destroying opened sliding doors causes the game to crash.

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#939] opened 2024-02-05 12:06 UTC
Minecraft: 1.20.1 (Tested on singleplayer without any mods except for LittleTiles and CreativeCore)
Forge: 47.2.20
LittleTiles: 1.6.0 pre-89
CreativeCore: 2.11.23

As the title suggests, destroying opened sliding doors causes the game to crash.

A video i've recorded showcasing the bug:
(...)

Steps to replicate:
1. Go into creative mode
2. Create a sliding door using the Little Blueprint tool with any preferences you want, just make sure right click is enabled
3. Place the sliding door wherever you want to
4. Open the sliding door using right click
5. Destroy the opened sliding door using left click
6. Crash with feature placement error "java.lang.RuntimeException: We are asking a region for a chunk out of bound | -134217728 134217725"

Here's the crash report:
[link]

**Comment by CreativeMD** [comment] 2024-02-09 17:27
That is a weird issue. Are you far away from spawn?

**Comment by ghost** [comment] 2024-02-09 19:21
Not necessarily, the coordinates are x74 y133 z257 and no matter how far i moved away from that spot and got closer to my spawn area i still got the error.
However i have experimented for a little bit and found out that the game tends to produce this crash: "The game crashed whilst exception generating new chunk Error: java.lang.ArrayIndexOutOfBoundsException: Index -536870611 out of bounds for length 315" on worlds with the worldtype set to default, and superflat worlds with a selected preset (in my case Overworld) tend to produce this crash: "java.lang.RuntimeException: We are asking a region for a chunk out of bound | -134217728 134217725".

**Comment by CreativeMD** [comment] 2024-02-16 09:11
Can you update CreativeCore and LittleTiles and see if the issue is still there?

**Comment by ghost** [comment] 2024-02-16 14:45
The game continues to crash with this message - "The game crashed whilst feature placement Error: java.lang.RuntimeException: We are asking a region for a chunk out of bound | -134217728 134217725"
Here is the crash report - [link]

**Comment by CreativeMD** [comment] 2024-02-16 15:45
The crash is pretty weird, because I cannot even see what mods are included ...
Is it possible for you to send me your world so I can test it myself?

**Comment by ghost** [comment] 2024-02-16 16:16
Sure, but just so you're aware, i had to use the re-create feature for the original world used in my showcase of the bug because it was too big and it wouldn't let me upload it - [link]

**Comment by CreativeMD** [comment] 2024-02-17 21:53
Thanks a lot for your help. This made it quite easy to reproduce. It is fixed in the newest version!

**Closed as completed by CreativeMD** 2024-02-17 21:53 UTC
