### ISSUE TITLE
Placing blocks of any size consumes entire blocks

### ISSUE THREAD

**Issue by Terra777** [CreativeMD/LittleTiles#758] opened 2021-10-11 14:26 UTC
LittleTiles_v1.5.28_mc1.12.2.jar
CreativeCore_v1.10.65_mc1.12.2.jar
Bug.

> Placing down smaller block of any size causes a full block to be used instead of a "pixel or a small part of the block".
> Placing blocks into the little tiles back consumes the blocks fully.
> The issue appears both in modded and vanilla blocks.
> Used Little Chisel

**Comment by CreativeMD** [comment] 2021-10-14 08:19
Can you show an example? I tested it myself and it works just fine. Also keep in mind if you have a little bag, it will automatically put the remaining block parts in there.

**Comment by Terra777** [comment] 2021-10-14 08:37
Okay, so i went to version 1.5.24 and it doesn't happen, but in 28 it does happen for me, i will see to provide a few screenshots or a video to show whats going on.

**Comment by Terra777** [comment] 2021-10-14 08:55
https://youtu.be/5C7fgm0fQ10

This is link to an unlisted youtube video.

This is what happens, considering it didn't happen to you id say its a bug involving an inventory sorting mod or sth judging by behavior seen. It is just weird it doesnt happen before 1.5.24. (i didnt try versions between 1.5.24 and 28). I also included my settings, i got a pretty powerful pc so keep that in mind. Also, i play modpacks in this case FoolCraft 3. Never had an issue before this tho.

**Comment by Terra777** [comment] 2021-10-14 08:57
Made sure/double checked that the versions of the mods i used are as mentioned up there.
LittleTiles_v1.5.28_mc1.12.2.jar
CreativeCore_v1.10.65_mc1.12.2.jar

**Comment by TheBlueCrystal** [comment] 2021-10-14 22:03
Hello,
perhaps I did find the reason for the "disappearing" tiles in the code. If I'm not mistaken, the culprit is commit 1e0c936c05abb7793515a46f5ab54977fbc2f85c ('Fixed not loading bags correctly').
It changes the direction of the compare operator in file com/creativemd/littletiles/common/item/ItemLittleBag.java line 97
LittleGridContext.getMax().pixelVolume is the smallest size a tile can get regarding to the selected scale.
In my opinion the original direction of the compare-operator was correct. It says that if the tile to be added is "bigger" than the smalest possible tile volume it will be added to the stack. After the "fix" this semantic is inverted and so no tile will ever be added to the bag (except it is smaller than the minimal possible tile size, which only could happen, if one changed the scale in the meanwhile).

**Comment by CreativeMD** [comment] 2021-10-15 08:16
@TheBlueCrystal Thanks for the hint!
A different issue caused this weird behavior, so I changed the operator, which fixed the issue ... in hindsight I should have looked more closely. The issue was caused by an infinite pixel volume of the highest grid. All grids beyond 1024 exceed the int limit with their tiles inside one block count. This let to a pixel volume of 1/0 --> infinity. I have these grids enabled for testing purposes, it's obviously not recommended to use them anyway. I changed the count to a long which fixes the issue and reverted the operator again.

Thanks for reporting this issue and for all the help! It's fixed in the newest version.

**Closed as completed by CreativeMD** 2021-10-15 08:16 UTC
