### ISSUE TITLE
cant join server with littletiles

### ISSUE THREAD

**Issue by Xplodin** [CreativeMD/LittleTiles#894] opened 2023-09-22 02:59 UTC
am unsure why or what the error means but this is what happens when joining my server
![image](https://github.com/CreativeMD/LittleTiles/assets/13007677/e78eeabc-ab3e-42e5-9e73-377cf2de1030)

**Comment by FoxMcloud5655** [comment] 2023-09-22 11:51
Can confirm this issue happens on dedicated servers.  Version is 1.6.0-pre61.

**Comment by FoxMcloud5655** [comment] 2023-09-22 11:58
The actual error is as follows:
```
Error executing task on Client
java.lang.NullPointerException: Cannot load from object array because "team.creative.littletiles.common.grid.LittleGrid.grids" is null
	at team.creative.littletiles.common.grid.LittleGrid.defaultGrid(LittleGrid.java:101) ~[LittleTiles_ALPHA_v1.6.0-pre061_mc1.20.1.jar%23594!/:1.6.0-pre061]
	at team.creative.littletiles.common.placement.setting.PlacementPlayerSetting.<init>(PlacementPlayerSetting.java:18) ~[LittleTiles_ALPHA_v1.6.0-pre061_mc1.20.1.jar%23594!/:1.6.0-pre061]
	at team.creative.littletiles.client.action.LittleActionHandlerClient.<init>(LittleActionHandlerClient.java:28) ~[LittleTiles_ALPHA_v1.6.0-pre061_mc1.20.1.jar%23594!/:1.6.0-pre061]
	at team.creative.littletiles.client.level.LevelHandlersClient$LevelHandlerClient.load(LevelHandlersClient.java:50) ~[LittleTiles_ALPHA_v1.6.0-pre061_mc1.20.1.jar%23594!/:1.6.0-pre061]
	at team.creative.littletiles.client.level.LevelHandlersClient.load(LevelHandlersClient.java:37) ~[LittleTiles_ALPHA_v1.6.0-pre061_mc1.20.1.jar%23594!/:1.6.0-pre061]
```
Very likely caused by commit [24aee5b](https://github.com/CreativeMD/LittleTiles/commit/24aee5bf7cc942e6bc934fa1d1fea6150df59c3c#diff-a184696234d1362ea747fc57be7f29a9ac58d696c077dd97dff344300c564218)

**Comment by CreativeMD** [comment] 2023-09-23 16:28
Fixed in the newest version! Thanks for taking the time to report this issue and providing the need information!

**Closed as completed by CreativeMD** 2023-09-23 16:28 UTC
