### ISSUE TITLE
Crash 16Oct2020

### ISSUE THREAD

**Issue by Potsukin** [CreativeMD/LittleTiles#512] opened 2020-10-16 10:28 UTC
https://pastebin.com/Sunq5bkj

**Comment by CreativeMD** [comment] 2020-10-17 18:28
There must be some kind of issue with the gui, I need your log file. Maybe it happens because you enabled stencil again?

**Comment by Potsukin** [comment] 2020-10-17 22:21
I have never edited a Stencil in the past.
[2020-10-15-6.log.gz](https://github.com/CreativeMD/LittleTiles/files/5396799/2020-10-15-6.log.gz)

**Comment by Potsukin** [comment] 2020-10-17 22:26
Fill mode does not work properly is happening to me too. Try testing with intricate shapes

**Comment by Potsukin** [comment] 2020-10-17 22:43
This is probably a very rare bug. When I changed the shape to Cylinder, nothing other than Shape was displayed, so when I closed the window, Minecraft shut down. It happens many times, so I tried throwing away the Little Chisel and replacing it with a new one, but it didn't happen.

**Comment by CreativeMD** [comment] 2020-10-18 08:21
Pretty sure this is not the right log file. I need the crashed one. I recommend to reproduce this issue and send the latest.log.

**Comment by Potsukin** [comment] 2020-10-18 09:35
It is nearly impossible to reproduce this bug. It was happened in one Little Chisel in sudden, others was not. The error hasn't occurred since I replacing it with a new one.

**Comment by CreativeMD** [comment] 2020-10-18 10:26
Ok, I will close this issue for now. If it happens again, make sure to send me your log file.

**Closed as completed by CreativeMD** 2020-10-18 10:26 UTC

**Comment by Potsukin** [comment] 2020-10-18 10:29
I was thinking of doing the same thing. The version is also 65 and may have been fixed. I will report any of the same bugs.
