### ISSUE TITLE
Invisible little/tiles in ver LT64 ( CreativeCore28 )

### ISSUE THREAD

**Issue by Gixuu** [CreativeMD/LittleTiles#510] opened 2020-10-16 08:42 UTC
They just become invisible after few minutes or randomly. I don't know what it cause, the structure is still there. The render region is off.
[latest.log](https://github.com/CreativeMD/LittleTiles/files/5390322/latest.log)

Builder's+Tools+-+1.2.0
CreativeCore_v1.10.28_mc1.12.2
LittleTiles_v1.5.0-pre199_64_mc1.12.2
Optifine_1.12.2_HD_U_F5

**Comment by CreativeMD** [comment] 2020-10-17 18:04
This is a duplicate of https://github.com/CreativeMD/LittleTiles/issues/506 can you please post your config file there? I actually need all the configs (also the vanilla and optifine ones).

**Closed as completed by CreativeMD** 2020-10-17 18:04 UTC
