### ISSUE TITLE
Advanced doors that are in the open state disappear when chunk is unloaded

### ISSUE THREAD

**Issue by Catz1301** [CreativeMD/LittleTiles#447] opened 2020-07-22 16:30 UTC
Whenever you create an advanced door with an advanced recipe, and then you place it, it will disappear once its chunk is unloaded.

**To Reproduce**
1. Create an object. Any object will do.
2. Make it an advanced door with an advanced recipe.
3. Configure it to move around for a little bit, having its offset start and stop on different axis (This is what I did).
4. Activate the door.
5. Wait for it to finish 'opening'.
6. Leave the chunk so that the chunk will unload.
7. Come back to it after a few seconds.
8. Voila. The door has done its magical disappearing trick. You now need a new door.

**Expected behavior**
The door should have been in its same spot as before you left the chunk.

**Screenshots**

**Desktop (please complete the following information):**
 - Java version: 
 - Forge version: 
 - Minecraft version: 

**Additional context**
I was playing in a server environment, in survival, I can't recreate it in my own test environment, but I will get a list of mods used.

**Comment by kirokadura** [comment] 2020-07-23 15:11
What kind of server API are you using? Mohist or Magma, by any chance?

**Comment by Catz1301** [comment] 2020-08-03 21:21
None, just forge.

**Comment by CreativeMD** [comment] 2020-08-28 20:23
What LittleTiles version are you using? Can you provide me your log files?

**Comment by CreativeMD** [comment] 2020-09-04 08:53
Maybe it was caused by spawn protection, since I cannot reproduce this issue. I will close it for now. If it happens again make sure to post it here including some more information. Thanks for taking your time to report this issue, really hope it doesn't occur again.

**Closed as completed by CreativeMD** 2020-09-04 08:53 UTC
