### ISSUE TITLE
Error executing task

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#640] opened 2021-04-19 20:10 UTC
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_252]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_252]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:467) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_252]
        at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_252]
        at net.minecraftforge.event.world.BlockEvent$MultiPlaceEvent.<init>(BlockEvent.java:284) ~[BlockEvent$MultiPlaceEvent.class:?]
        at com.creativemd.littletiles.common.util.place.Placement.place(Placement.java:165) ~[Placement.class:?]
        at com.creativemd.littletiles.common.action.block.LittleActionPlaceStack.placeTile(LittleActionPlaceStack.java:148) ~[LittleActionPlaceStack.class:?]
        at com.creativemd.littletiles.common.action.block.LittleActionPlaceStack.action(LittleActionPlaceStack.java:100) ~[LittleActionPlaceStack.class:?]
        at com.creativemd.littletiles.common.action.LittleAction.executeServer(LittleAction.java:307) ~[LittleAction.class:?]
        at com.creativemd.creativecore.common.packet.PacketReciever$2.run(PacketReciever.java:117) ~[PacketReciever$2.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_252]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_252]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more

Latest Little Tiles 1.5.2

**Comment by Desoroxxx** [comment] 2021-04-19 20:22
Please post a crash report

**Comment by ghost** [comment] 2021-04-20 11:05
There was no Crash. I think console errors can reportet to. Because they may trigger a crash at some point.

**Comment by Desoroxxx** [comment] 2021-04-20 11:32
The problem is that what other mods do you have it's important also the forge version.

**Comment by CreativeMD** [comment] 2021-04-22 08:23
Please update to the newest CreativeCore and LittleTiles version, if the issue still appears make sure to send me the entire log file. Will close this issue for now.

**Closed as completed by CreativeMD** 2021-04-22 08:23 UTC
