### ISSUE TITLE
Tile preview does not show up sometimes

### ISSUE THREAD

**Issue by jericjan** [CreativeMD/LittleTiles#172] opened 2019-05-17 01:43 UTC
When I'm holding a tile or a chisel, the tile preview that should show will sometimes not show up. 

screenshots:
https://imgur.com/a/g4nx0Ct

Also, how can I combine tiles? It doesn't work with the wrench anymore.

**Comment by CreativeMD** [comment] 2019-05-17 08:38
That's caused by the shader. Unfortunately there is nothing I can do about it. Some shaders work others only work partially.

It's right click with a wrench. Can you explain a little bit further what it doesn't work anymore means?

**Comment by CreativeMD** [comment] 2019-05-20 12:59
I will close the issue for now. Just let me know if the second issue still persists (as posted earlier).

**Closed as completed by CreativeMD** 2019-05-20 12:59 UTC
