### ISSUE TITLE
Littletiles not rendering.

### ISSUE THREAD

**Issue by infiniteblock** [CreativeMD/LittleTiles#422] opened 2020-06-10 17:46 UTC
Made a grate to sit above cc:tweaked network cable once u logout of world and back in it wont render its just invisible. also happens with elevator block from elevator mod.

CreativeCore_v1.10.16_mc1.12.2
LittleTiles_v1.5.0-pre199_34_mc1.12.2

``{tiles:[{boxes:[[I;14,0,0,16,1,16],[I;0,0,0,2,1,16],[I;2,0,12,14,1,13],[I;2,0,10,14,1,11],[I;2,0,8,14,1,9],[I;2,0,6,14,1,7],[I;2,0,4,14,1,5],[I;2,0,2,14,1,3],[I;2,0,0,14,1,1],[I;2,0,14,14,1,15]],tile:{block:"warpdrive:hull.superior.plain:15"}}],min:[I;0,0,0],size:[I;16,1,16],count:10,structure:{name:"grate",id:"fixed"}}``

https://cdn.discordapp.com/attachments/276752435869908993/720331134281711627/2020-06-11_05.38.15.png

https://media.discordapp.net/attachments/276752435869908993/720327650585083944/2020-06-11_05.24.11.png?width=1276&height=677

**Comment by CreativeMD** [comment] 2020-06-12 20:36
I would need the list of all the mods you are using. Looks like it's an issue with another mod, especially if the elevator mod is broken as well.

**Comment by MBarnulf** [comment] 2020-06-30 23:43
I have the same problem, in 1.12.2 with little tile 1.5.0, optifine F5 and forge 14.23.5.2854, there is my mod list (sorry for the length)

```
AdditionalEnchantedMiner 12.3.9
anvilpatch 1.0.0
appliedenergistics2 rv6 stable 7
Armourers Workshop 0.50.1
alternate terrain generation 2.5.0
autooredictconv 1.12 1.0.1
Baubles 1.12 1.5.2
betteranimalsplus 9.0.1
BetterFoliage 1.12 2.2.0
BetterFps 1.4.8
BetterRecords 1.6.2
BiblioCraft v2.4.5
Bookshelf 2.3.585
Botania r1.10 361
Chameleon 1.12 4.1.3
champions 1.0.11.8
Chisel 1.0.2.45
ChunkAnimator 1.12 1.2
ClaySoldiersMod 3.0.0 beta.2
CodeChickenLib 3.2.3.358
CoFHCore 4.6.6.1
CoFHWorld 1.4.0.1
ColossalChests 1.7.3
compactmachines3 3.0.18 b278
craftingstation 0.1.7c
CraftTweaker2 1.12 4.1.20.574
CreativeCore v1.10.16
creeperconfetti 1.4.2
CTM 1.0.2.31
Cucumber 1.1.3
CustomNPCs 01Oct19
cxlibrary 1.12.1 1.6.1
CyclopsCore 1.6.4
Dalek Mod Update 57.1
DimensionalDoors 3.0.9 287
DynamicDynamos 1.10
DynamicSurroundings 3.6.1.0
EnchantingPlus 5.0.176
EnchantmentDescriptions 1.1.20
EnderCore 0.5.75
EnderIO 5.1.55
EnderStorage 2.4.6.137
energyconverters 1.3.6.24
environmentaltech 2.0.20.1
EvenMoreTNT 1.0.1
extrautils2 1.12 1.9.9
ExtremeReactors 0.4.5.67
FamiliarFauna 1.0.11
findme 1.1.0 8
Flan's Mod 5.5.1 .disable
foamfix 0.10.10
Forgelin 1.8.4
fossilsarcheology 8.0.4
furniture 6.3.1
future 0.2.3.2
Galacticraft Planets 4.0.2.280
GalacticraftCore 4.0.2.280
Guide API 1.12 2.1.8 63
GunpowderLib 1.0
Hwyla 1.8.26 B41
ICBM classic 3.3.0b63
iChunUtil 7.2.2
ImmersiveEngineering 0.12 92
industrialcraft 2 2.8.170 ex112
industrialforegoing 1.12.13 237
instantunify 1.1.2
IntegrationForegoing 1.10
InventoryTweaks 1.63
IronBackpacks 3.0.8 12
ironchest 7.0.72.847
ItemPhysic Full 1.4.34
IvToolkit 1.3.3 1.12
jei 4.15.0.291
LagGoggles 5.8 132
lemonlib 1.2.1
LittleTiles v1.5.0 pre199 34
living enchantment 3.2.1
llibrary 1.7.19
LootOverhaul 1.2 .disable
luckyblock 7.6.0.zi
luckyores 1.3
malisiscore 6.5.1
malisisdoors 7.3.0
MatterOverdrive 0.7.1.0
jtylib 1.12 3.5.4
mdecore 1.12 1.1
Mekanism 9.8.3.390
Mercurius
MicdoodleCore 4.0.2.280
MobAmputation 7.0.1
MobDismemberment 7.0.0
MoreFurnaces 1.10.6
morepaintings paintings 5.0.1.2
MorePlayerModels 05Dec19
MultiMine
MultiPageChest 1.12 1.9.1
mw 1.11.7.7
MysticalAgriculture 1.7.5
noRecipeBook v1.2.2for
NotEnoughItems 2.4.3.245
omlib 3.1.4 249
ompd 3.1.0 61
OpenBlocks 1.8.1
OpenComputers 1.7.5.192
OpenModsLib 0.12.2
openmodularturrets 3.1.10 371
OptiFine HD U F5
oredictreorder 1.0.0
OreLib 3.6.0.1
Overlord 2.4.14
phosphor 0.2.6 build50
PiTweaks 1.12 1.1.1
randomloot 1.7.4
randompatches 1.21.0.3
randomtweaks 2.8.0.2
reauth 3.6.0
RecurrentComplex 1.4.8.2
RedstoneArsenal 2.6.6.1
RedstoneFlux 1.12 2.1.1.1
reskin 1.2.0
resynth 1.3.8
Rex's Additional Structures 1.12.x v.2.3.1
rftools 1.12 7.73
rftoolsctrl 1.12 2.0.2
rftoolsdim 1.12 5.71
rftoolspower 1.12 1.2.0
RoguelikeDungeons 1.8.0
RTG 6.1.0.0 snapshot.1
SanLib 1.5.1
SereneSeasons 1.2.18
ShoulderSurfing 1.15.1
SimplyJetpacks2 2.2.14.67
somanyenchantments V0.4.31
SoundFilters 0.12 for 1.12
statues rechiseled 1.0.1
StorageDrawers 5.4.2
superores 1.9.0 1.12
Surge 2.0.77
Sync 7.1.0
techguns 2.0.2.0 pre3.2
tesla core lib 1.0.17
TexFix V 1.12 4.0
ThermalDynamics 2.5.6.1
ThermalExpansion 5.5.7.1
ThermalFoundation 2.6.7.1
ThermalInnovation 0.3.6.1
thermallogistics 0.2 29
TickCentral 2.6
valkyriecompat 2.0.20.1
valkyrielib 2.0.20.1
VariedCommodities 21nov19
Xaeros Minimap 20.12.1 Forge 1.12
XPFromHarvest 1.2.0
zerocore 0.1.2.8
bspkrsCore 7.6.0.1
TreeCapitator client 1.43.0
```

If it is too difficult to process it, I can try to test with parts of it until I get the "patch" of mods causing the glitch

**Comment by CreativeMD** [comment] 2020-07-08 09:12
@MajorBarnulf no tiles render at all or only the structure mentioned above?

Not all blocks can be rendered, some modded blocks are not entirely compatible with LT. To make sure it's not caused by another mod you could only install CreativeCore, LittleTiles and the elevator mod. If it still doesn't render you can't use this block unfortunately.

**Comment by Tschipp** [comment] 2020-07-13 09:09
A suspicion from my end: I recently added FoamFix to my pack, about the same time the issue also started occuring. I see that you are also using FoamFix, maybe removing it fixes it.

**Comment by MBarnulf** [comment] 2020-07-14 17:28
@CreativeMD all tiles render at first, but when I quit my server and come back, certain of them doesn't render,
it doesn't seem to be related to the material or the shape, because I have multiples instances of the same structure made with tiles of the same blocks and the same shapes.
parts of them doesn't render, but it's always a different part, like if the render of tiles was chosen randomly :/

**Comment by CreativeMD** [comment] 2020-08-28 20:01
Can you test the newest version?
https://cdn.discordapp.com/attachments/326729168266199040/748915793831657502/CreativeCore_v1.10.18_mc1.12.2.jar
https://cdn.discordapp.com/attachments/326729168266199040/748915823812280422/LittleTiles_v1.5.0-pre199_41_mc1.12.2.jar
https://cdn.discordapp.com/attachments/326729168266199040/745705002861068319/OnlinePicFrame_v1.5.0-pre1_mc1.12.2.jar

**Comment by CreativeMD** [comment] 2020-09-04 09:44
This issue should finally be fixed using the newest pre-release on the discord server. Finally found the small mistake which caused it to happen from time to time.

I will release it on curseforge as soon as it's stable enough.

**Comment by MBarnulf** [comment] 2020-09-04 13:37
> This issue should finally be fixed using the newest pre-release on the discord server. Finally found the small mistake which caused it to happen from time to time.
> 
> I will release it on curseforge as soon as it's stable enough.

thank you a lot for your work, if it fixes it, this mod will finally be able to get that prestige and reputation it deserves!
(I am currently testing the files on my worlds and servers)



- EDIT:
- [x] after a lot of testing, I can finally say that the problem is solved in my case

**Comment by CreativeMD** [comment] 2020-09-17 13:37
Fixed in the neweset pre-release on curseforge (make sure to update CreativeCore as well).

**Closed as completed by CreativeMD** 2020-09-17 13:37 UTC
