### ISSUE TITLE
harvestLevelBlock seems to not work.

### ISSUE THREAD

**Issue by SlayerTheChikken** [CreativeMD/LittleTiles#647] opened 2021-04-22 11:25 UTC
I changed harvestLevelBlock to 1 in every single section of the config (I tried just survival at first,) and you can still break obsidian with a single click with the little hammer, the other settings seem to work fine.

**Comment by SlayerTheChikken** [comment] 2021-04-22 12:49
https://github.com/CreativeMD/LittleTiles/issues/609 also stated here, not sure what's going wrong but the issue is valid I think.

**Comment by CreativeMD** [comment] 2021-04-23 13:53
Can you show me your config file? I tested it, setting it to level 1 makes it impossible for me to mine obsidian with the hammer (in creative).

**Comment by SlayerTheChikken** [comment] 2021-04-24 07:36
[littletiles.txt](https://github.com/CreativeMD/LittleTiles/files/6369140/littletiles.txt)

**Comment by CreativeMD** [comment] 2021-04-24 07:52
Are you using this on a server? And you configured it ingame? I just can't reproduce it because it works fine for me.

**Comment by SlayerTheChikken** [comment] 2021-04-24 07:53
I edited the config, closed game, then saved config, then went ingame, this is singleplayer

**Comment by SlayerTheChikken** [comment] 2021-04-24 08:00
I just tried it again and in the newest version there is also a crash when trying to select blocks so... I'll go ahead and open that issue report ;-; I never really had any issues with littletiles ever so this is strange for me XD

**Comment by CreativeMD** [comment] 2021-04-24 08:02
Use the command /cmdconfig, no need to edit the config file.

**Comment by SlayerTheChikken** [comment] 2021-04-24 08:10
I'm going to update both littletiles and creativecore again and retest all of this, I could have swore I updated creativecore but apparently not, my sleep is kinda screwed rn so I'm sorry for the mistakes :/

**Comment by SlayerTheChikken** [comment] 2021-04-24 08:23
Okay so I deleted the old configs, the old mod versions, then added the updated versions, went ingame, edited the configs using the command, restarted the game, and it still doesn't seem to work..

**Comment by SlayerTheChikken** [comment] 2021-04-24 08:24
[littletiles.json.txt](https://github.com/CreativeMD/LittleTiles/files/6369236/littletiles.json.txt)
(I have to upload these as .txt files because github denies .json)

**Comment by SlayerTheChikken** [comment] 2021-04-24 08:29
Okay I tested without any other mods besides littleframes and creativecore and this still seems to be the case, what version of forge for 1.12.2 do you use for internal testing?

**Comment by CreativeMD** [comment] 2021-04-26 08:47
Just keep in mind that this configuration only affects vanilla blocks not tiles. It makes it impossible to cut/ edit these blocks.
Also no need to restart anything.

**Comment by CreativeMD** [comment] 2021-04-30 16:23
Will close this issue for now. If this issue still persists just let me know here.

**Closed as completed by CreativeMD** 2021-04-30 16:23 UTC
