### ISSUE TITLE
Some faces of overlapping slices not rendering

### ISSUE THREAD

**Issue by QBFreak** [CreativeMD/LittleTiles#232] opened 2019-08-09 23:46 UTC
## Description

Overlapping slices in specific circumstances prevent one of the faces of one of the slices from being rendered.

This occurs with or without Optifine.

## Steps to reproduce

Import and place the following recipe: 
[slice-graphical-glitch.txt](https://github.com/CreativeMD/LittleTiles/files/3488279/slice-graphical-glitch.txt)

The failure should look like this:

![slice-graphical-glitch](https://user-images.githubusercontent.com/17347092/62814335-35d26e00-bade-11e9-932f-50eb3a3c560e.png)

## Expected Behavior

All visible faces of all slices should be rendered.

## Details
|| Versions |
|--|--|
| **Minecraft:** | 1.12.2 |
| **Forge:** | 14.23.5.2838 |
| **LittleTiles:** | 1.5.0-pre158 |
| **CreativeCore:** | 1.9.62 |
| **Other mods:** | No, reproducible with just LittleTiles |

**Comment by CreativeMD** [comment] 2019-08-13 09:00
![](https://i.imgur.com/32w0AgY.png)

All sides work just fine for me. Even tried to rotate it, but still could not reproduce this issue. Can you send me your world?

**Comment by CreativeMD** [comment] 2019-09-29 15:23
I will close this issue for now, as I could not reproduce it. If it still persists just reopen it.

**Closed as completed by CreativeMD** 2019-09-29 15:23 UTC
Labels: Bug
